// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sdktoken.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SDK的唯一标识
type SDKToken struct {
	Ip      string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Pid     uint32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Uid     string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Client  string `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	//该sdkContext所属进程运行的容器pod
	PodName string `protobuf:"bytes,6,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	//该sdkContext所属进程所属容器或者机器的hostname
	HostName             string   `protobuf:"bytes,7,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SDKToken) Reset()         { *m = SDKToken{} }
func (m *SDKToken) String() string { return proto.CompactTextString(m) }
func (*SDKToken) ProtoMessage()    {}
func (*SDKToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_f270bea404f71a38, []int{0}
}

func (m *SDKToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDKToken.Unmarshal(m, b)
}
func (m *SDKToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDKToken.Marshal(b, m, deterministic)
}
func (m *SDKToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDKToken.Merge(m, src)
}
func (m *SDKToken) XXX_Size() int {
	return xxx_messageInfo_SDKToken.Size(m)
}
func (m *SDKToken) XXX_DiscardUnknown() {
	xxx_messageInfo_SDKToken.DiscardUnknown(m)
}

var xxx_messageInfo_SDKToken proto.InternalMessageInfo

func (m *SDKToken) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *SDKToken) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *SDKToken) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SDKToken) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *SDKToken) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SDKToken) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *SDKToken) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func init() {
	proto.RegisterType((*SDKToken)(nil), "v1.SDKToken")
}

func init() { proto.RegisterFile("sdktoken.proto", fileDescriptor_f270bea404f71a38) }

var fileDescriptor_f270bea404f71a38 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4e, 0xc9, 0x2e,
	0xc9, 0xcf, 0x4e, 0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x54, 0x5a,
	0xc1, 0xc8, 0xc5, 0x11, 0xec, 0xe2, 0x1d, 0x02, 0x12, 0x16, 0xe2, 0xe3, 0x62, 0xca, 0x2c, 0x90,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x2c, 0x10, 0x12, 0xe0, 0x62, 0x2e, 0xc8, 0x4c,
	0x91, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0d, 0x02, 0x31, 0x41, 0x22, 0xa5, 0x99, 0x29, 0x12, 0xcc,
	0x60, 0x25, 0x20, 0xa6, 0x90, 0x18, 0x17, 0x5b, 0x72, 0x4e, 0x66, 0x6a, 0x5e, 0x89, 0x04, 0x0b,
	0x58, 0x10, 0xca, 0x13, 0x92, 0xe0, 0x62, 0x2f, 0x4b, 0x2d, 0x2a, 0xce, 0xcc, 0xcf, 0x93, 0x60,
	0x05, 0x4b, 0xc0, 0xb8, 0x42, 0x92, 0x5c, 0x1c, 0x05, 0xf9, 0x29, 0xf1, 0x79, 0x89, 0xb9, 0xa9,
	0x12, 0x6c, 0x10, 0xa9, 0x82, 0xfc, 0x14, 0xbf, 0xc4, 0xdc, 0x54, 0x21, 0x69, 0x2e, 0xce, 0x8c,
	0xfc, 0xe2, 0x12, 0x88, 0x1c, 0x3b, 0x58, 0x8e, 0x03, 0x24, 0x00, 0x92, 0x4c, 0x62, 0x03, 0xbb,
	0xda, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xa2, 0xeb, 0x25, 0xc7, 0x00, 0x00, 0x00,
}
