apiVersion: v1
kind: Service
metadata:
  name: examples-go-nearby-consumer
  namespace: default
  labels:
    app: consumer
spec:
  ports:
    - port: 28080
      targetPort: 28080
  selector:
    app: consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - image: polarismesh/examples-go-nearby-consumer:latest
          imagePullPolicy: Always
          name: polaris-consumer
          env:
            - name: POLARIS_INSTANCE_REGION
              value: china
            - name: POLARIS_INSTANCE_ZONE
              value: ap-guangzhou
            - name: POLARIS_INSTANCE_CAMPUS
              value: ap-guangzhou-1
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /root/polaris.yaml
              name: polaris-consumer-config
              subPath: polaris.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: polaris-consumer-config
          name: polaris-consumer-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - image: polarismesh/examples-go-nearby-consumer:latest
          imagePullPolicy: Always
          name: polaris-consumer
          env:
            - name: POLARIS_INSTANCE_REGION
              value: china
            - name: POLARIS_INSTANCE_ZONE
              value: ap-guangzhou
            - name: POLARIS_INSTANCE_CAMPUS
              value: ap-guangzhou-2
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /root/polaris.yaml
              name: polaris-consumer-config
              subPath: polaris.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: polaris-consumer-config
          name: polaris-consumer-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - image: polarismesh/examples-go-nearby-consumer:latest
          imagePullPolicy: Always
          name: polaris-consumer
          env:
            - name: POLARIS_INSTANCE_REGION
              value: china
            - name: POLARIS_INSTANCE_ZONE
              value: ap-guangzhou
            - name: POLARIS_INSTANCE_CAMPUS
              value: ap-guangzhou-3
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /root/polaris.yaml
              name: polaris-consumer-config
              subPath: polaris.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: polaris-consumer-config
          name: polaris-consumer-config
