apiVersion: v1
kind: Service
metadata:
  name: examples-go-nearby-provider
  namespace: default
  labels:
    app: provider
spec:
  ports:
    - port: 28080
      targetPort: 28080
  selector:
    app: provider
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-1
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - image: polarismesh/examples-go-nearby-provider:latest
        imagePullPolicy: Always
        name: polaris-provider
        env:
        - name: POLARIS_INSTANCE_REGION
          value: china
        - name: POLARIS_INSTANCE_ZONE
          value: ap-guangzhou
        - name: POLARIS_INSTANCE_CAMPUS
          value: ap-guangzhou-1
        resources:
          limits:
            cpu: "500m"
            memory: 1000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/polaris.yaml
          name: polaris-provider-config
          subPath: polaris.yaml
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: polaris-provider-config
        name: polaris-provider-config

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-2
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - image: polarismesh/examples-go-nearby-provider:latest
        imagePullPolicy: Always
        name: polaris-provider
        env:
        - name: POLARIS_INSTANCE_REGION
          value: china
        - name: POLARIS_INSTANCE_ZONE
          value: ap-guangzhou
        - name: POLARIS_INSTANCE_CAMPUS
          value: ap-guangzhou-2
        resources:
          limits:
            cpu: "500m"
            memory: 1000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/polaris.yaml
          name: polaris-provider-config
          subPath: polaris.yaml
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: polaris-provider-config
        name: polaris-provider-config

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-3
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - image: polarismesh/examples-go-nearby-provider:latest
        imagePullPolicy: Always
        name: polaris-provider
        env:
        - name: POLARIS_INSTANCE_REGION
          value: china
        - name: POLARIS_INSTANCE_ZONE
          value: ap-guangzhou
        - name: POLARIS_INSTANCE_CAMPUS
          value: ap-guangzhou-3
        resources:
          limits:
            cpu: "500m"
            memory: 1000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/polaris.yaml
          name: polaris-provider-config
          subPath: polaris.yaml
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: polaris-provider-config
        name: polaris-provider-config


