// Code generated by protoc-gen-go.
// source: sidecar.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	sidecar.proto

It has these top-level messages:
	GetOneInstanceRequest
	GetOneInstanceResponse
	Response
	ServiceCallResult
	BatchServiceCallResult
	RegisterInstanceRequest
	DeregisterInstanceRequest
	InstanceHeartbeatRequest
	DetailErrInfo
*/
package pb

import (
	"fmt"
	"math"

	"github.com/golang/protobuf/proto"
	google_protobuf "github.com/golang/protobuf/ptypes/wrappers"

	_ "github.com/polarismesh/polaris-go/pkg/model/pb/v1"
	v11 "github.com/polarismesh/polaris-go/pkg/model/pb/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// polaris 获取单个实例请求
type GetOneInstanceRequest struct {
	Namespace   *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	ServiceName *google_protobuf.StringValue `protobuf:"bytes,2,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
}

func (m *GetOneInstanceRequest) Reset()                    { *m = GetOneInstanceRequest{} }
func (m *GetOneInstanceRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOneInstanceRequest) ProtoMessage()               {}
func (*GetOneInstanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetOneInstanceRequest) GetNamespace() *google_protobuf.StringValue {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *GetOneInstanceRequest) GetServiceName() *google_protobuf.StringValue {
	if m != nil {
		return m.ServiceName
	}
	return nil
}

// polaris 获取单个实例返回
type GetOneInstanceResponse struct {
	Instance *v11.Instance `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
}

func (m *GetOneInstanceResponse) Reset()                    { *m = GetOneInstanceResponse{} }
func (m *GetOneInstanceResponse) String() string            { return proto.CompactTextString(m) }
func (*GetOneInstanceResponse) ProtoMessage()               {}
func (*GetOneInstanceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetOneInstanceResponse) GetInstance() *v11.Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

// 通用response返回
type Response struct {
	DnsCode           int32  `protobuf:"varint,1,opt,name=dns_code,json=dnsCode" json:"dns_code,omitempty"`
	PolarisCode       int32  `protobuf:"varint,2,opt,name=polaris_code,json=polarisCode" json:"polaris_code,omitempty"`
	PolarisDetailInfo string `protobuf:"bytes,3,opt,name=polaris_detail_info,json=polarisDetailInfo" json:"polaris_detail_info,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetDnsCode() int32 {
	if m != nil {
		return m.DnsCode
	}
	return 0
}

func (m *Response) GetPolarisCode() int32 {
	if m != nil {
		return m.PolarisCode
	}
	return 0
}

func (m *Response) GetPolarisDetailInfo() string {
	if m != nil {
		return m.PolarisDetailInfo
	}
	return ""
}

// 用于用户调用结果上报
type ServiceCallResult struct {
	Instance *v11.Instance `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	// 必选，本地服务调用的状态，正常or异常
	RetStatus int32 `protobuf:"varint,2,opt,name=ret_status,json=retStatus" json:"ret_status,omitempty"`
	// 必选，本地服务调用的返回码
	RetCode int32 `protobuf:"varint,3,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	// 必选，被调服务实例获取接口的最大时延
	TimeDelay int64 `protobuf:"varint,4,opt,name=time_delay,json=timeDelay" json:"time_delay,omitempty"`
}

func (m *ServiceCallResult) Reset()                    { *m = ServiceCallResult{} }
func (m *ServiceCallResult) String() string            { return proto.CompactTextString(m) }
func (*ServiceCallResult) ProtoMessage()               {}
func (*ServiceCallResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ServiceCallResult) GetInstance() *v11.Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *ServiceCallResult) GetRetStatus() int32 {
	if m != nil {
		return m.RetStatus
	}
	return 0
}

func (m *ServiceCallResult) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ServiceCallResult) GetTimeDelay() int64 {
	if m != nil {
		return m.TimeDelay
	}
	return 0
}

// 批量发送用户调用结果
type BatchServiceCallResult struct {
	CallResults []*ServiceCallResult `protobuf:"bytes,1,rep,name=call_results,json=callResults" json:"call_results,omitempty"`
}

func (m *BatchServiceCallResult) Reset()                    { *m = BatchServiceCallResult{} }
func (m *BatchServiceCallResult) String() string            { return proto.CompactTextString(m) }
func (*BatchServiceCallResult) ProtoMessage()               {}
func (*BatchServiceCallResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BatchServiceCallResult) GetCallResults() []*ServiceCallResult {
	if m != nil {
		return m.CallResults
	}
	return nil
}

// 注册服务
type RegisterInstanceRequest struct {
	Instance *v11.Instance `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
}

func (m *RegisterInstanceRequest) Reset()                    { *m = RegisterInstanceRequest{} }
func (m *RegisterInstanceRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterInstanceRequest) ProtoMessage()               {}
func (*RegisterInstanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RegisterInstanceRequest) GetInstance() *v11.Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

// 反注册服务
type DeregisterInstanceRequest struct {
	Instance *v11.Instance `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
}

func (m *DeregisterInstanceRequest) Reset()                    { *m = DeregisterInstanceRequest{} }
func (m *DeregisterInstanceRequest) String() string            { return proto.CompactTextString(m) }
func (*DeregisterInstanceRequest) ProtoMessage()               {}
func (*DeregisterInstanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeregisterInstanceRequest) GetInstance() *v11.Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

// 心跳
type InstanceHeartbeatRequest struct {
	Instance *v11.Instance `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
}

func (m *InstanceHeartbeatRequest) Reset()                    { *m = InstanceHeartbeatRequest{} }
func (m *InstanceHeartbeatRequest) String() string            { return proto.CompactTextString(m) }
func (*InstanceHeartbeatRequest) ProtoMessage()               {}
func (*InstanceHeartbeatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *InstanceHeartbeatRequest) GetInstance() *v11.Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

// 详细的错误信息
type DetailErrInfo struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg" json:"err_msg,omitempty"`
}

func (m *DetailErrInfo) Reset()                    { *m = DetailErrInfo{} }
func (m *DetailErrInfo) String() string            { return proto.CompactTextString(m) }
func (*DetailErrInfo) ProtoMessage()               {}
func (*DetailErrInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DetailErrInfo) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *DetailErrInfo) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*GetOneInstanceRequest)(nil), "pb.GetOneInstanceRequest")
	proto.RegisterType((*GetOneInstanceResponse)(nil), "pb.GetOneInstanceResponse")
	proto.RegisterType((*Response)(nil), "pb.response")
	proto.RegisterType((*ServiceCallResult)(nil), "pb.ServiceCallResult")
	proto.RegisterType((*BatchServiceCallResult)(nil), "pb.BatchServiceCallResult")
	proto.RegisterType((*RegisterInstanceRequest)(nil), "pb.RegisterInstanceRequest")
	proto.RegisterType((*DeregisterInstanceRequest)(nil), "pb.DeregisterInstanceRequest")
	proto.RegisterType((*InstanceHeartbeatRequest)(nil), "pb.InstanceHeartbeatRequest")
	proto.RegisterType((*DetailErrInfo)(nil), "pb.DetailErrInfo")
}

func init() { proto.RegisterFile("sidecar.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x6f, 0xd3, 0x4e,
	0x10, 0xc5, 0xe5, 0xe4, 0xff, 0x6f, 0x93, 0x71, 0x82, 0x54, 0x57, 0x6d, 0xdd, 0x8a, 0xa2, 0xe0,
	0x53, 0x4e, 0xae, 0x28, 0x17, 0xc4, 0x05, 0xa9, 0x49, 0x05, 0x3d, 0x00, 0xd2, 0x46, 0xe2, 0x6a,
	0xad, 0xed, 0x89, 0x59, 0x69, 0xbd, 0x6b, 0x66, 0xd7, 0x05, 0xbe, 0x07, 0xe2, 0xf3, 0x22, 0xaf,
	0xd7, 0xa9, 0xd4, 0x5e, 0x82, 0xb8, 0xed, 0xbc, 0xf7, 0x76, 0xf5, 0x9b, 0x9d, 0x81, 0xb9, 0x11,
	0x25, 0x16, 0x9c, 0xd2, 0x86, 0xb4, 0xd5, 0xd1, 0xa8, 0xc9, 0x2f, 0x5e, 0x54, 0x5a, 0x57, 0x12,
	0xaf, 0x9c, 0x92, 0xb7, 0xdb, 0xab, 0xef, 0xc4, 0x9b, 0x06, 0xc9, 0xf4, 0x99, 0x8b, 0xb9, 0x41,
	0xba, 0x17, 0x05, 0x0e, 0x25, 0xe9, 0xd6, 0x0a, 0x55, 0xf9, 0xf2, 0x98, 0xb8, 0x45, 0x29, 0x6a,
	0x61, 0xa9, 0x95, 0x43, 0x26, 0xac, 0x75, 0x89, 0xd2, 0x17, 0xcf, 0x08, 0x4d, 0xa3, 0x95, 0xf1,
	0x66, 0xf2, 0x2b, 0x80, 0x93, 0xf7, 0x68, 0x3f, 0x2b, 0xbc, 0x53, 0xc6, 0x72, 0x55, 0x20, 0xc3,
	0x6f, 0x2d, 0x1a, 0x1b, 0xbd, 0x85, 0xa9, 0xe2, 0x35, 0x9a, 0x86, 0x17, 0x18, 0x07, 0x8b, 0x60,
	0x19, 0x5e, 0x3f, 0x4f, 0x7b, 0xba, 0x74, 0xa0, 0x4b, 0x37, 0x96, 0x84, 0xaa, 0xbe, 0x70, 0xd9,
	0x22, 0x7b, 0x88, 0x47, 0xef, 0x60, 0xe6, 0x39, 0xb3, 0x4e, 0x8c, 0x47, 0x7b, 0x5c, 0x0f, 0xfd,
	0x8d, 0x4f, 0xbc, 0xc6, 0xe4, 0x06, 0x4e, 0x1f, 0x53, 0xf5, 0xd8, 0xd1, 0x12, 0x26, 0xc2, 0x6b,
	0x9e, 0x6a, 0x96, 0xde, 0xbf, 0x4a, 0x77, 0xb9, 0x9d, 0x9b, 0xfc, 0x80, 0xc9, 0xd0, 0x6c, 0x74,
	0x0e, 0x93, 0x52, 0x99, 0xac, 0xd0, 0x65, 0x7f, 0xeb, 0x7f, 0x76, 0x58, 0x2a, 0xb3, 0xd2, 0x25,
	0x46, 0x2f, 0x61, 0xd6, 0x68, 0xc9, 0x49, 0x78, 0x7b, 0xe4, 0xec, 0xd0, 0x6b, 0x2e, 0x92, 0xc2,
	0xf1, 0x10, 0x29, 0xd1, 0x72, 0x21, 0x33, 0xa1, 0xb6, 0x3a, 0x1e, 0x2f, 0x82, 0xe5, 0x94, 0x1d,
	0x79, 0x6b, 0xed, 0x9c, 0x3b, 0xb5, 0xd5, 0xc9, 0xef, 0x00, 0x8e, 0x36, 0x7d, 0x37, 0x2b, 0x2e,
	0x25, 0x43, 0xd3, 0x4a, 0xbb, 0x3f, 0x79, 0x74, 0x09, 0x40, 0x68, 0x33, 0x63, 0xb9, 0x6d, 0x8d,
	0x07, 0x9a, 0x12, 0xda, 0x8d, 0x13, 0xba, 0x66, 0x3a, 0xdb, 0xd1, 0x8e, 0xfb, 0x66, 0x08, 0xad,
	0x23, 0xbd, 0x04, 0xb0, 0xa2, 0xc6, 0xac, 0x44, 0xc9, 0x7f, 0xc6, 0xff, 0x2d, 0x82, 0xe5, 0x98,
	0x4d, 0x3b, 0x65, 0xdd, 0x09, 0x09, 0x83, 0xd3, 0x1b, 0x6e, 0x8b, 0xaf, 0x4f, 0xe1, 0xde, 0xc0,
	0xac, 0xe0, 0x52, 0x66, 0xe4, 0x4a, 0x13, 0x07, 0x8b, 0xf1, 0x32, 0xbc, 0x3e, 0x49, 0x9b, 0x3c,
	0x7d, 0x12, 0x66, 0x61, 0xb1, 0x3b, 0x9b, 0x64, 0x05, 0x67, 0x0c, 0x2b, 0x61, 0x2c, 0xd2, 0xe3,
	0x15, 0xda, 0x7f, 0x56, 0xb7, 0x70, 0xbe, 0x46, 0xfa, 0xe7, 0x67, 0xd6, 0x10, 0x0f, 0xea, 0x07,
	0xe4, 0x64, 0x73, 0xe4, 0xf6, 0xef, 0x5f, 0x59, 0xc1, 0xbc, 0x1f, 0xe6, 0x2d, 0x51, 0x37, 0xcf,
	0xee, 0xc3, 0x91, 0xe8, 0x61, 0x7b, 0xe6, 0xec, 0x10, 0x89, 0xdc, 0x87, 0x9f, 0x41, 0x77, 0xcc,
	0x6a, 0x53, 0xb9, 0x39, 0x4d, 0xd9, 0x01, 0x12, 0x7d, 0x34, 0x55, 0x7e, 0xe0, 0x96, 0xfc, 0xf5,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x61, 0x55, 0xea, 0x83, 0xe4, 0x03, 0x00, 0x00,
}
