// Code generated by protoc-gen-go. DO NOT EDIT.
// source: polaris_response.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DiscoverResponse_DiscoverResponseType int32

const (
	DiscoverResponse_UNKNOWN     DiscoverResponse_DiscoverResponseType = 0
	DiscoverResponse_INSTANCE    DiscoverResponse_DiscoverResponseType = 1
	DiscoverResponse_CLUSTER     DiscoverResponse_DiscoverResponseType = 2
	DiscoverResponse_ROUTING     DiscoverResponse_DiscoverResponseType = 3
	DiscoverResponse_RATE_LIMIT  DiscoverResponse_DiscoverResponseType = 4
	DiscoverResponse_SERVICES    DiscoverResponse_DiscoverResponseType = 6
	DiscoverResponse_MESH        DiscoverResponse_DiscoverResponseType = 7
	DiscoverResponse_MESH_CONFIG DiscoverResponse_DiscoverResponseType = 8
)

var DiscoverResponse_DiscoverResponseType_name = map[int32]string{
	0: "UNKNOWN",
	1: "INSTANCE",
	2: "CLUSTER",
	3: "ROUTING",
	4: "RATE_LIMIT",
	6: "SERVICES",
	7: "MESH",
	8: "MESH_CONFIG",
}
var DiscoverResponse_DiscoverResponseType_value = map[string]int32{
	"UNKNOWN":     0,
	"INSTANCE":    1,
	"CLUSTER":     2,
	"ROUTING":     3,
	"RATE_LIMIT":  4,
	"SERVICES":    6,
	"MESH":        7,
	"MESH_CONFIG": 8,
}

func (x DiscoverResponse_DiscoverResponseType) String() string {
	return proto.EnumName(DiscoverResponse_DiscoverResponseType_name, int32(x))
}
func (DiscoverResponse_DiscoverResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_polaris_response_2442b548c98abb37, []int{4, 0}
}

type SimpleResponse struct {
	Code                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SimpleResponse) Reset()         { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()    {}
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_response_2442b548c98abb37, []int{0}
}
func (m *SimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse.Unmarshal(m, b)
}
func (m *SimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse.Marshal(b, m, deterministic)
}
func (dst *SimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse.Merge(dst, src)
}
func (m *SimpleResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse.Size(m)
}
func (m *SimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse proto.InternalMessageInfo

func (m *SimpleResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *SimpleResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

type Response struct {
	Code                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Client               *Client               `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	Namespace            *Namespace            `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service              *Service              `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	Instance             *Instance             `protobuf:"bytes,6,opt,name=instance,proto3" json:"instance,omitempty"`
	Routing              *Routing              `protobuf:"bytes,7,opt,name=routing,proto3" json:"routing,omitempty"`
	Alias                *ServiceAlias         `protobuf:"bytes,8,opt,name=alias,proto3" json:"alias,omitempty"`
	RateLimit            *Rule                 `protobuf:"bytes,9,opt,name=rateLimit,proto3" json:"rateLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_response_2442b548c98abb37, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Response) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Response) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *Response) GetNamespace() *Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *Response) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Response) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *Response) GetRouting() *Routing {
	if m != nil {
		return m.Routing
	}
	return nil
}

func (m *Response) GetAlias() *ServiceAlias {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *Response) GetRateLimit() *Rule {
	if m != nil {
		return m.RateLimit
	}
	return nil
}

type BatchWriteResponse struct {
	Code                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Size                 *wrappers.UInt32Value `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Responses            []*Response           `protobuf:"bytes,4,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BatchWriteResponse) Reset()         { *m = BatchWriteResponse{} }
func (m *BatchWriteResponse) String() string { return proto.CompactTextString(m) }
func (*BatchWriteResponse) ProtoMessage()    {}
func (*BatchWriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_response_2442b548c98abb37, []int{2}
}
func (m *BatchWriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchWriteResponse.Unmarshal(m, b)
}
func (m *BatchWriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchWriteResponse.Marshal(b, m, deterministic)
}
func (dst *BatchWriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchWriteResponse.Merge(dst, src)
}
func (m *BatchWriteResponse) XXX_Size() int {
	return xxx_messageInfo_BatchWriteResponse.Size(m)
}
func (m *BatchWriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchWriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchWriteResponse proto.InternalMessageInfo

func (m *BatchWriteResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *BatchWriteResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *BatchWriteResponse) GetSize() *wrappers.UInt32Value {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *BatchWriteResponse) GetResponses() []*Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

type BatchQueryResponse struct {
	Code                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Amount               *wrappers.UInt32Value `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Size                 *wrappers.UInt32Value `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Namespaces           []*Namespace          `protobuf:"bytes,5,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Services             []*Service            `protobuf:"bytes,6,rep,name=services,proto3" json:"services,omitempty"`
	Instances            []*Instance           `protobuf:"bytes,7,rep,name=instances,proto3" json:"instances,omitempty"`
	Routings             []*Routing            `protobuf:"bytes,8,rep,name=routings,proto3" json:"routings,omitempty"`
	Aliases              []*ServiceAlias       `protobuf:"bytes,9,rep,name=aliases,proto3" json:"aliases,omitempty"`
	RateLimits           []*Rule               `protobuf:"bytes,10,rep,name=rateLimits,proto3" json:"rateLimits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BatchQueryResponse) Reset()         { *m = BatchQueryResponse{} }
func (m *BatchQueryResponse) String() string { return proto.CompactTextString(m) }
func (*BatchQueryResponse) ProtoMessage()    {}
func (*BatchQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_response_2442b548c98abb37, []int{3}
}
func (m *BatchQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchQueryResponse.Unmarshal(m, b)
}
func (m *BatchQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchQueryResponse.Marshal(b, m, deterministic)
}
func (dst *BatchQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchQueryResponse.Merge(dst, src)
}
func (m *BatchQueryResponse) XXX_Size() int {
	return xxx_messageInfo_BatchQueryResponse.Size(m)
}
func (m *BatchQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchQueryResponse proto.InternalMessageInfo

func (m *BatchQueryResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *BatchQueryResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *BatchQueryResponse) GetAmount() *wrappers.UInt32Value {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *BatchQueryResponse) GetSize() *wrappers.UInt32Value {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *BatchQueryResponse) GetNamespaces() []*Namespace {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

func (m *BatchQueryResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *BatchQueryResponse) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *BatchQueryResponse) GetRoutings() []*Routing {
	if m != nil {
		return m.Routings
	}
	return nil
}

func (m *BatchQueryResponse) GetAliases() []*ServiceAlias {
	if m != nil {
		return m.Aliases
	}
	return nil
}

func (m *BatchQueryResponse) GetRateLimits() []*Rule {
	if m != nil {
		return m.RateLimits
	}
	return nil
}

type DiscoverResponse struct {
	Code                 *wrappers.UInt32Value                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue                 `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Type                 DiscoverResponse_DiscoverResponseType `protobuf:"varint,3,opt,name=type,proto3,enum=v1.DiscoverResponse_DiscoverResponseType" json:"type,omitempty"`
	Service              *Service                              `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Instances            []*Instance                           `protobuf:"bytes,5,rep,name=instances,proto3" json:"instances,omitempty"`
	Routing              *Routing                              `protobuf:"bytes,6,opt,name=routing,proto3" json:"routing,omitempty"`
	RateLimit            *RateLimit                            `protobuf:"bytes,7,opt,name=rateLimit,proto3" json:"rateLimit,omitempty"`
	Services             []*Service                            `protobuf:"bytes,9,rep,name=services,proto3" json:"services,omitempty"`
	Mesh                 *Mesh                                 `protobuf:"bytes,10,opt,name=mesh,proto3" json:"mesh,omitempty"`
	Meshconfig           *MeshConfig                           `protobuf:"bytes,11,opt,name=meshconfig,proto3" json:"meshconfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *DiscoverResponse) Reset()         { *m = DiscoverResponse{} }
func (m *DiscoverResponse) String() string { return proto.CompactTextString(m) }
func (*DiscoverResponse) ProtoMessage()    {}
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_response_2442b548c98abb37, []int{4}
}
func (m *DiscoverResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverResponse.Unmarshal(m, b)
}
func (m *DiscoverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverResponse.Marshal(b, m, deterministic)
}
func (dst *DiscoverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverResponse.Merge(dst, src)
}
func (m *DiscoverResponse) XXX_Size() int {
	return xxx_messageInfo_DiscoverResponse.Size(m)
}
func (m *DiscoverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverResponse proto.InternalMessageInfo

func (m *DiscoverResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *DiscoverResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *DiscoverResponse) GetType() DiscoverResponse_DiscoverResponseType {
	if m != nil {
		return m.Type
	}
	return DiscoverResponse_UNKNOWN
}

func (m *DiscoverResponse) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *DiscoverResponse) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *DiscoverResponse) GetRouting() *Routing {
	if m != nil {
		return m.Routing
	}
	return nil
}

func (m *DiscoverResponse) GetRateLimit() *RateLimit {
	if m != nil {
		return m.RateLimit
	}
	return nil
}

func (m *DiscoverResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *DiscoverResponse) GetMesh() *Mesh {
	if m != nil {
		return m.Mesh
	}
	return nil
}

func (m *DiscoverResponse) GetMeshconfig() *MeshConfig {
	if m != nil {
		return m.Meshconfig
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleResponse)(nil), "v1.SimpleResponse")
	proto.RegisterType((*Response)(nil), "v1.Response")
	proto.RegisterType((*BatchWriteResponse)(nil), "v1.BatchWriteResponse")
	proto.RegisterType((*BatchQueryResponse)(nil), "v1.BatchQueryResponse")
	proto.RegisterType((*DiscoverResponse)(nil), "v1.DiscoverResponse")
	proto.RegisterEnum("v1.DiscoverResponse_DiscoverResponseType", DiscoverResponse_DiscoverResponseType_name, DiscoverResponse_DiscoverResponseType_value)
}

func init() {
	proto.RegisterFile("polaris_response.proto", fileDescriptor_polaris_response_2442b548c98abb37)
}

var fileDescriptor_polaris_response_2442b548c98abb37 = []byte{
	// 700 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xfd, 0xa5, 0x71, 0x12, 0x67, 0xd2, 0x5f, 0xb0, 0x56, 0x05, 0xad, 0x4a, 0x85, 0xaa, 0x48,
	0x94, 0xd2, 0x8a, 0x94, 0xb6, 0x5c, 0x39, 0x94, 0x10, 0x8a, 0x45, 0xeb, 0x8a, 0x75, 0xd2, 0x1e,
	0x2b, 0xd7, 0x6c, 0xd3, 0x95, 0x1c, 0xdb, 0xf2, 0xda, 0x41, 0xe5, 0x8c, 0xc4, 0x37, 0xe4, 0xc0,
	0x95, 0x2f, 0x82, 0x76, 0xbd, 0x6b, 0xbb, 0x29, 0x04, 0x4e, 0xb9, 0x25, 0xef, 0xbd, 0xf9, 0xe3,
	0x99, 0xe7, 0x31, 0x3c, 0x8a, 0xa3, 0xc0, 0x4b, 0x18, 0xbf, 0x4c, 0x28, 0x8f, 0xa3, 0x90, 0xd3,
	0x7e, 0x9c, 0x44, 0x69, 0x84, 0x56, 0x66, 0xfb, 0xeb, 0x4f, 0x26, 0x51, 0x34, 0x09, 0xe8, 0x9e,
	0x44, 0xae, 0xb2, 0xeb, 0xbd, 0xcf, 0x89, 0x17, 0xc7, 0x34, 0xe1, 0xb9, 0x66, 0xfd, 0xa1, 0x8e,
	0xe5, 0x34, 0x99, 0x31, 0x9f, 0xce, 0xc3, 0x49, 0x94, 0xa5, 0x2c, 0x9c, 0x28, 0x78, 0x4d, 0xc3,
	0x7e, 0xc0, 0x68, 0x98, 0x2a, 0xf4, 0x71, 0x21, 0xf6, 0x52, 0x1a, 0xb0, 0x29, 0x4b, 0x93, 0x2c,
	0xd0, 0x99, 0xac, 0x29, 0xe5, 0x37, 0x7e, 0x14, 0x5e, 0x33, 0x95, 0xa4, 0x97, 0x42, 0xd7, 0x65,
	0xd3, 0x38, 0xa0, 0x44, 0xb5, 0x8b, 0x5e, 0x82, 0xe1, 0x47, 0x9f, 0x28, 0xae, 0x6d, 0xd6, 0xb6,
	0x3b, 0x07, 0x1b, 0xfd, 0xbc, 0xe7, 0xbe, 0xee, 0xb9, 0x3f, 0xb6, 0xc3, 0xf4, 0xf0, 0xe0, 0xdc,
	0x0b, 0x32, 0x4a, 0xa4, 0x52, 0x44, 0xb0, 0xf0, 0x3a, 0xc2, 0x2b, 0x7f, 0x88, 0x70, 0xd3, 0x84,
	0x85, 0x13, 0x15, 0x21, 0x94, 0xbd, 0x6f, 0x75, 0x30, 0x97, 0x59, 0x10, 0xf5, 0xa0, 0x99, 0x4f,
	0x09, 0xd7, 0x65, 0x0c, 0xf4, 0x67, 0xfb, 0xfd, 0x81, 0x44, 0x88, 0x62, 0xd0, 0x2e, 0xb4, 0x43,
	0x6f, 0x4a, 0x79, 0xec, 0xf9, 0x14, 0x1b, 0x52, 0xf6, 0xbf, 0x90, 0x39, 0x1a, 0x24, 0x25, 0x8f,
	0x9e, 0x42, 0x4b, 0x2d, 0x09, 0x37, 0xa4, 0xb4, 0x23, 0xa4, 0x6e, 0x0e, 0x11, 0xcd, 0xa1, 0x6d,
	0x30, 0x59, 0xc8, 0x53, 0x2f, 0xf4, 0x29, 0x6e, 0x4a, 0xdd, 0xaa, 0xd0, 0xd9, 0x0a, 0x23, 0x05,
	0x2b, 0x12, 0xaa, 0xf5, 0xe2, 0x56, 0x99, 0x90, 0xe4, 0x10, 0xd1, 0x1c, 0xda, 0x82, 0x86, 0x17,
	0x30, 0x8f, 0x63, 0x53, 0x8a, 0xac, 0x4a, 0xd5, 0x23, 0x81, 0x93, 0x9c, 0x46, 0x5b, 0xd0, 0x16,
	0x06, 0x38, 0x11, 0x06, 0xc0, 0x6d, 0xa9, 0x35, 0x65, 0xc2, 0x2c, 0xa0, 0xa4, 0xa4, 0x7a, 0xdf,
	0x6b, 0x80, 0xde, 0x78, 0xa9, 0x7f, 0x73, 0x91, 0xb0, 0x74, 0xa9, 0x26, 0x10, 0x11, 0x9c, 0x7d,
	0xa1, 0x6a, 0x23, 0x7f, 0xa9, 0x21, 0x94, 0x68, 0x07, 0xda, 0xfa, 0xad, 0xe2, 0xd8, 0xd8, 0xac,
	0xeb, 0x71, 0xea, 0xb6, 0x49, 0x49, 0xf7, 0x7e, 0xd6, 0xd5, 0x83, 0x7d, 0xcc, 0x68, 0x72, 0xbb,
	0xd4, 0x07, 0x7b, 0x05, 0x4d, 0x6f, 0x1a, 0x65, 0x85, 0xd9, 0x16, 0x57, 0x51, 0xda, 0x62, 0x1c,
	0xc6, 0x3f, 0x8f, 0xe3, 0x05, 0x40, 0x61, 0x48, 0x8e, 0x1b, 0x72, 0x1e, 0x73, 0x8e, 0xad, 0x08,
	0xd0, 0x33, 0x30, 0x95, 0x2d, 0x39, 0x6e, 0x4a, 0xf1, 0x1d, 0xcf, 0x16, 0xa4, 0x18, 0xb3, 0xb6,
	0x25, 0xc7, 0xad, 0x72, 0xcc, 0x85, 0x6b, 0x4b, 0x5a, 0x24, 0x55, 0xd6, 0x14, 0x96, 0xac, 0xcf,
	0xfb, 0xb6, 0x20, 0xd1, 0x0e, 0xb4, 0xa4, 0x33, 0x29, 0xc7, 0x6d, 0xa9, 0xbb, 0x6f, 0x5d, 0x2d,
	0x40, 0xdb, 0x00, 0x85, 0x43, 0x39, 0x06, 0x29, 0x2f, 0xdd, 0x5b, 0xe1, 0x7a, 0x3f, 0x0c, 0xb0,
	0xde, 0x32, 0xee, 0x47, 0x33, 0x9a, 0x2c, 0x75, 0xc7, 0xaf, 0xc1, 0x48, 0x6f, 0xe3, 0xdc, 0xbc,
	0xdd, 0x83, 0xe7, 0xa2, 0xb9, 0xf9, 0x3e, 0xee, 0x01, 0xa3, 0xdb, 0x98, 0x12, 0x19, 0x56, 0x3d,
	0x1f, 0xc6, 0x82, 0xf3, 0x71, 0x67, 0x13, 0x8d, 0xc5, 0x9b, 0xa8, 0x1c, 0x90, 0xe6, 0x82, 0x03,
	0xb2, 0x5b, 0x3d, 0x0c, 0xad, 0xf2, 0xca, 0x11, 0x0d, 0x56, 0xae, 0xc3, 0x1d, 0xcb, 0xb4, 0x17,
	0x59, 0x66, 0x03, 0x0c, 0xf1, 0x69, 0xc1, 0x50, 0x5e, 0x9a, 0x53, 0xca, 0x6f, 0x88, 0x44, 0x51,
	0x1f, 0xa0, 0xfc, 0xf0, 0xe0, 0x8e, 0xd4, 0x74, 0xb5, 0x66, 0x20, 0x51, 0x52, 0x51, 0xf4, 0xbe,
	0xd6, 0x60, 0xed, 0x77, 0xc3, 0x43, 0x1d, 0x68, 0x8d, 0x9d, 0x0f, 0xce, 0xd9, 0x85, 0x63, 0xfd,
	0x87, 0x56, 0xc1, 0xb4, 0x1d, 0x77, 0x74, 0xe4, 0x0c, 0x86, 0x56, 0x4d, 0x50, 0x83, 0x93, 0xb1,
	0x3b, 0x1a, 0x12, 0x6b, 0x45, 0xfc, 0x21, 0x67, 0xe3, 0x91, 0xed, 0x1c, 0x5b, 0x75, 0xd4, 0x05,
	0x20, 0x47, 0xa3, 0xe1, 0xe5, 0x89, 0x7d, 0x6a, 0x8f, 0x2c, 0x43, 0xc4, 0xb9, 0x43, 0x72, 0x6e,
	0x0f, 0x86, 0xae, 0xd5, 0x44, 0x26, 0x18, 0xa7, 0x43, 0xf7, 0xbd, 0xd5, 0x42, 0x0f, 0xa0, 0x23,
	0x7e, 0x5d, 0x0e, 0xce, 0x9c, 0x77, 0xf6, 0xb1, 0x65, 0x5e, 0x35, 0xe5, 0xfe, 0x0f, 0x7f, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xc8, 0xe3, 0x55, 0xf5, 0xd3, 0x07, 0x00, 0x00,
}
