// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcapi_v2.proto

package v2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RateLimitGRPCV2Client is the client API for RateLimitGRPCV2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RateLimitGRPCV2Client interface {
	// 限流接口
	Service(ctx context.Context, opts ...grpc.CallOption) (RateLimitGRPCV2_ServiceClient, error)
	// 时间对齐接口
	TimeAdjust(ctx context.Context, in *TimeAdjustRequest, opts ...grpc.CallOption) (*TimeAdjustResponse, error)
}

type rateLimitGRPCV2Client struct {
	cc *grpc.ClientConn
}

func NewRateLimitGRPCV2Client(cc *grpc.ClientConn) RateLimitGRPCV2Client {
	return &rateLimitGRPCV2Client{cc}
}

func (c *rateLimitGRPCV2Client) Service(ctx context.Context, opts ...grpc.CallOption) (RateLimitGRPCV2_ServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RateLimitGRPCV2_serviceDesc.Streams[0], "/polaris.metric.v2.RateLimitGRPCV2/Service", opts...)
	if err != nil {
		return nil, err
	}
	x := &rateLimitGRPCV2ServiceClient{stream}
	return x, nil
}

type RateLimitGRPCV2_ServiceClient interface {
	Send(*RateLimitRequest) error
	Recv() (*RateLimitResponse, error)
	grpc.ClientStream
}

type rateLimitGRPCV2ServiceClient struct {
	grpc.ClientStream
}

func (x *rateLimitGRPCV2ServiceClient) Send(m *RateLimitRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *rateLimitGRPCV2ServiceClient) Recv() (*RateLimitResponse, error) {
	m := new(RateLimitResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rateLimitGRPCV2Client) TimeAdjust(ctx context.Context, in *TimeAdjustRequest, opts ...grpc.CallOption) (*TimeAdjustResponse, error) {
	out := new(TimeAdjustResponse)
	err := c.cc.Invoke(ctx, "/polaris.metric.v2.RateLimitGRPCV2/TimeAdjust", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RateLimitGRPCV2Server is the server API for RateLimitGRPCV2 service.
type RateLimitGRPCV2Server interface {
	// 限流接口
	Service(RateLimitGRPCV2_ServiceServer) error
	// 时间对齐接口
	TimeAdjust(context.Context, *TimeAdjustRequest) (*TimeAdjustResponse, error)
}

func RegisterRateLimitGRPCV2Server(s *grpc.Server, srv RateLimitGRPCV2Server) {
	s.RegisterService(&_RateLimitGRPCV2_serviceDesc, srv)
}

func _RateLimitGRPCV2_Service_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RateLimitGRPCV2Server).Service(&rateLimitGRPCV2ServiceServer{stream})
}

type RateLimitGRPCV2_ServiceServer interface {
	Send(*RateLimitResponse) error
	Recv() (*RateLimitRequest, error)
	grpc.ServerStream
}

type rateLimitGRPCV2ServiceServer struct {
	grpc.ServerStream
}

func (x *rateLimitGRPCV2ServiceServer) Send(m *RateLimitResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *rateLimitGRPCV2ServiceServer) Recv() (*RateLimitRequest, error) {
	m := new(RateLimitRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RateLimitGRPCV2_TimeAdjust_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeAdjustRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimitGRPCV2Server).TimeAdjust(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/polaris.metric.v2.RateLimitGRPCV2/TimeAdjust",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimitGRPCV2Server).TimeAdjust(ctx, req.(*TimeAdjustRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RateLimitGRPCV2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "polaris.metric.v2.RateLimitGRPCV2",
	HandlerType: (*RateLimitGRPCV2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TimeAdjust",
			Handler:    _RateLimitGRPCV2_TimeAdjust_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Service",
			Handler:       _RateLimitGRPCV2_Service_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpcapi_v2.proto",
}

func init() { proto.RegisterFile("grpcapi_v2.proto", fileDescriptor_grpcapi_v2_8d4acbd844a4895d) }

var fileDescriptor_grpcapi_v2_8d4acbd844a4895d = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x2f, 0x2a, 0x48,
	0x4e, 0x2c, 0xc8, 0x8c, 0x2f, 0x33, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2c, 0xc8,
	0xcf, 0x49, 0x2c, 0xca, 0x2c, 0xd6, 0xcb, 0x4d, 0x2d, 0x29, 0xca, 0x4c, 0xd6, 0x2b, 0x33, 0x92,
	0x12, 0x2a, 0x4a, 0x2c, 0x49, 0xcd, 0xc9, 0xcc, 0xcd, 0x2c, 0x81, 0x2b, 0x33, 0x3a, 0xc5, 0xc8,
	0xc5, 0x1f, 0x94, 0x58, 0x92, 0xea, 0x03, 0x12, 0x76, 0x0f, 0x0a, 0x70, 0x0e, 0x33, 0x12, 0x8a,
	0xe2, 0x62, 0x0f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0x52, 0xd6, 0xc3, 0x30, 0x46, 0x0f,
	0xae, 0x3c, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x4a, 0x05, 0xbf, 0xa2, 0xe2, 0x82, 0xfc,
	0xbc, 0xe2, 0x54, 0x25, 0x06, 0x0d, 0x46, 0x03, 0x46, 0xa1, 0x68, 0x2e, 0xae, 0x90, 0xcc, 0xdc,
	0x54, 0xc7, 0x94, 0xac, 0xd2, 0xe2, 0x12, 0x21, 0x6c, 0x3a, 0x11, 0xd2, 0x30, 0xf3, 0x55, 0x09,
	0xa8, 0x82, 0x59, 0xe0, 0xc4, 0x12, 0xc5, 0x54, 0x66, 0x94, 0xc4, 0x06, 0xf6, 0x99, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x32, 0xa2, 0xf5, 0xd1, 0x14, 0x01, 0x00, 0x00,
}
