// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitorresponse.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatResponse struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StatResponse) Reset()         { *m = StatResponse{} }
func (m *StatResponse) String() string { return proto.CompactTextString(m) }
func (*StatResponse) ProtoMessage()    {}
func (*StatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbca2e94dacd059f, []int{0}
}

func (m *StatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatResponse.Unmarshal(m, b)
}
func (m *StatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatResponse.Marshal(b, m, deterministic)
}
func (m *StatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatResponse.Merge(m, src)
}
func (m *StatResponse) XXX_Size() int {
	return xxx_messageInfo_StatResponse.Size(m)
}
func (m *StatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatResponse proto.InternalMessageInfo

func (m *StatResponse) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *StatResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *StatResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*StatResponse)(nil), "v1.StatResponse")
}

func init() { proto.RegisterFile("monitorresponse.proto", fileDescriptor_cbca2e94dacd059f) }

var fileDescriptor_cbca2e94dacd059f = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0xcd, 0xcf, 0xcb,
	0x2c, 0xc9, 0x2f, 0x2a, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x2a, 0x33, 0x94, 0x92, 0x4b, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b,
	0x24, 0x95, 0xa6, 0xe9, 0x97, 0x17, 0x25, 0x16, 0x14, 0xa4, 0x16, 0x15, 0x43, 0xd4, 0x28, 0x2d,
	0x60, 0xe4, 0xe2, 0x09, 0x2e, 0x49, 0x2c, 0x09, 0x82, 0x6a, 0x15, 0xd2, 0xe1, 0x62, 0xca, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd1, 0x83, 0xe8, 0xd6, 0x83, 0xe9, 0xd6, 0x0b,
	0x2e, 0x29, 0xca, 0xcc, 0x4b, 0x0f, 0x4b, 0xcc, 0x29, 0x4d, 0x0d, 0x62, 0xca, 0x4c, 0x11, 0x32,
	0xe0, 0x62, 0x49, 0xce, 0x4f, 0x49, 0x95, 0x60, 0xc2, 0xa1, 0x3e, 0xd4, 0x33, 0xaf, 0xc4, 0xd8,
	0x08, 0xa2, 0x1e, 0xac, 0x12, 0xa4, 0x23, 0x33, 0x2f, 0x2d, 0x5f, 0x82, 0x99, 0x08, 0x1b, 0xc0,
	0x2a, 0x93, 0xd8, 0xc0, 0x72, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x9d, 0xc8, 0x01,
	0xe6, 0x00, 0x00, 0x00,
}
