// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitorrequest.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//api接口调用
type APIResultType int32

const (
	//未知原因，更新pb后的sdk不得上报这种类型，用于兼容旧版本sdk
	APIResultType_UnknownType APIResultType = 0
	//用户调用成功
	APIResultType_Success APIResultType = 1
	//由于用户的原因，如参数错误导致的调用错误
	APIResultType_UserFail APIResultType = 2
	//由于系统原因（sdk或者server）导致用户调用失败
	APIResultType_PolarisFail APIResultType = 3
)

var APIResultType_name = map[int32]string{
	0: "UnknownType",
	1: "Success",
	2: "UserFail",
	3: "PolarisFail",
}

var APIResultType_value = map[string]int32{
	"UnknownType": 0,
	"Success":     1,
	"UserFail":    2,
	"PolarisFail": 3,
}

func (x APIResultType) String() string {
	return proto.EnumName(APIResultType_name, int32(x))
}

func (APIResultType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a075ef0672d1cf24, []int{0}
}

// polaris server上报的统计数据
type ServerStatistics struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  *ServerStatisticsKey  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                *Indicator            `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ServerStatistics) Reset()         { *m = ServerStatistics{} }
func (m *ServerStatistics) String() string { return proto.CompactTextString(m) }
func (*ServerStatistics) ProtoMessage()    {}
func (*ServerStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_a075ef0672d1cf24, []int{0}
}

func (m *ServerStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStatistics.Unmarshal(m, b)
}
func (m *ServerStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStatistics.Marshal(b, m, deterministic)
}
func (m *ServerStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStatistics.Merge(m, src)
}
func (m *ServerStatistics) XXX_Size() int {
	return xxx_messageInfo_ServerStatistics.Size(m)
}
func (m *ServerStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStatistics proto.InternalMessageInfo

func (m *ServerStatistics) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ServerStatistics) GetKey() *ServerStatisticsKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ServerStatistics) GetValue() *Indicator {
	if m != nil {
		return m.Value
	}
	return nil
}

type ServerStatisticsKey struct {
	ServerHost           *wrappers.StringValue `protobuf:"bytes,1,opt,name=server_host,json=serverHost,proto3" json:"server_host,omitempty"`
	Resource             *wrappers.StringValue `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Operation            *wrappers.StringValue `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Code                 *wrappers.StringValue `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Success              *wrappers.BoolValue   `protobuf:"bytes,5,opt,name=success,proto3" json:"success,omitempty"`
	DelayRange           *wrappers.StringValue `protobuf:"bytes,6,opt,name=delay_range,json=delayRange,proto3" json:"delay_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ServerStatisticsKey) Reset()         { *m = ServerStatisticsKey{} }
func (m *ServerStatisticsKey) String() string { return proto.CompactTextString(m) }
func (*ServerStatisticsKey) ProtoMessage()    {}
func (*ServerStatisticsKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_a075ef0672d1cf24, []int{1}
}

func (m *ServerStatisticsKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStatisticsKey.Unmarshal(m, b)
}
func (m *ServerStatisticsKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStatisticsKey.Marshal(b, m, deterministic)
}
func (m *ServerStatisticsKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStatisticsKey.Merge(m, src)
}
func (m *ServerStatisticsKey) XXX_Size() int {
	return xxx_messageInfo_ServerStatisticsKey.Size(m)
}
func (m *ServerStatisticsKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStatisticsKey.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStatisticsKey proto.InternalMessageInfo

func (m *ServerStatisticsKey) GetServerHost() *wrappers.StringValue {
	if m != nil {
		return m.ServerHost
	}
	return nil
}

func (m *ServerStatisticsKey) GetResource() *wrappers.StringValue {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *ServerStatisticsKey) GetOperation() *wrappers.StringValue {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *ServerStatisticsKey) GetCode() *wrappers.StringValue {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ServerStatisticsKey) GetSuccess() *wrappers.BoolValue {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *ServerStatisticsKey) GetDelayRange() *wrappers.StringValue {
	if m != nil {
		return m.DelayRange
	}
	return nil
}

// SDK上报的API调用统计
type SDKAPIStatistics struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  *SDKAPIStatisticsKey  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                *Indicator            `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SDKAPIStatistics) Reset()         { *m = SDKAPIStatistics{} }
func (m *SDKAPIStatistics) String() string { return proto.CompactTextString(m) }
func (*SDKAPIStatistics) ProtoMessage()    {}
func (*SDKAPIStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_a075ef0672d1cf24, []int{2}
}

func (m *SDKAPIStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDKAPIStatistics.Unmarshal(m, b)
}
func (m *SDKAPIStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDKAPIStatistics.Marshal(b, m, deterministic)
}
func (m *SDKAPIStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDKAPIStatistics.Merge(m, src)
}
func (m *SDKAPIStatistics) XXX_Size() int {
	return xxx_messageInfo_SDKAPIStatistics.Size(m)
}
func (m *SDKAPIStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_SDKAPIStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_SDKAPIStatistics proto.InternalMessageInfo

func (m *SDKAPIStatistics) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SDKAPIStatistics) GetKey() *SDKAPIStatisticsKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SDKAPIStatistics) GetValue() *Indicator {
	if m != nil {
		return m.Value
	}
	return nil
}

type SDKAPIStatisticsKey struct {
	ClientHost           *wrappers.StringValue `protobuf:"bytes,1,opt,name=client_host,json=clientHost,proto3" json:"client_host,omitempty"`
	SdkApi               *wrappers.StringValue `protobuf:"bytes,2,opt,name=sdk_api,json=sdkApi,proto3" json:"sdk_api,omitempty"`
	ResCode              *wrappers.StringValue `protobuf:"bytes,3,opt,name=res_code,json=resCode,proto3" json:"res_code,omitempty"`
	Success              *wrappers.BoolValue   `protobuf:"bytes,4,opt,name=success,proto3" json:"success,omitempty"`
	DelayRange           *wrappers.StringValue `protobuf:"bytes,5,opt,name=delay_range,json=delayRange,proto3" json:"delay_range,omitempty"`
	ClientVersion        *wrappers.StringValue `protobuf:"bytes,6,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ClientType           *wrappers.StringValue `protobuf:"bytes,7,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	Result               APIResultType         `protobuf:"varint,8,opt,name=result,proto3,enum=v1.APIResultType" json:"result,omitempty"`
	Uid                  string                `protobuf:"bytes,9,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SDKAPIStatisticsKey) Reset()         { *m = SDKAPIStatisticsKey{} }
func (m *SDKAPIStatisticsKey) String() string { return proto.CompactTextString(m) }
func (*SDKAPIStatisticsKey) ProtoMessage()    {}
func (*SDKAPIStatisticsKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_a075ef0672d1cf24, []int{3}
}

func (m *SDKAPIStatisticsKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDKAPIStatisticsKey.Unmarshal(m, b)
}
func (m *SDKAPIStatisticsKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDKAPIStatisticsKey.Marshal(b, m, deterministic)
}
func (m *SDKAPIStatisticsKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDKAPIStatisticsKey.Merge(m, src)
}
func (m *SDKAPIStatisticsKey) XXX_Size() int {
	return xxx_messageInfo_SDKAPIStatisticsKey.Size(m)
}
func (m *SDKAPIStatisticsKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SDKAPIStatisticsKey.DiscardUnknown(m)
}

var xxx_messageInfo_SDKAPIStatisticsKey proto.InternalMessageInfo

func (m *SDKAPIStatisticsKey) GetClientHost() *wrappers.StringValue {
	if m != nil {
		return m.ClientHost
	}
	return nil
}

func (m *SDKAPIStatisticsKey) GetSdkApi() *wrappers.StringValue {
	if m != nil {
		return m.SdkApi
	}
	return nil
}

func (m *SDKAPIStatisticsKey) GetResCode() *wrappers.StringValue {
	if m != nil {
		return m.ResCode
	}
	return nil
}

func (m *SDKAPIStatisticsKey) GetSuccess() *wrappers.BoolValue {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *SDKAPIStatisticsKey) GetDelayRange() *wrappers.StringValue {
	if m != nil {
		return m.DelayRange
	}
	return nil
}

func (m *SDKAPIStatisticsKey) GetClientVersion() *wrappers.StringValue {
	if m != nil {
		return m.ClientVersion
	}
	return nil
}

func (m *SDKAPIStatisticsKey) GetClientType() *wrappers.StringValue {
	if m != nil {
		return m.ClientType
	}
	return nil
}

func (m *SDKAPIStatisticsKey) GetResult() APIResultType {
	if m != nil {
		return m.Result
	}
	return APIResultType_UnknownType
}

func (m *SDKAPIStatisticsKey) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

// server和sdk的上报指标
type Indicator struct {
	TotalRequestPerMinute *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=total_request_per_minute,json=totalRequestPerMinute,proto3" json:"total_request_per_minute,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}              `json:"-"`
	XXX_unrecognized      []byte                `json:"-"`
	XXX_sizecache         int32                 `json:"-"`
}

func (m *Indicator) Reset()         { *m = Indicator{} }
func (m *Indicator) String() string { return proto.CompactTextString(m) }
func (*Indicator) ProtoMessage()    {}
func (*Indicator) Descriptor() ([]byte, []int) {
	return fileDescriptor_a075ef0672d1cf24, []int{4}
}

func (m *Indicator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Indicator.Unmarshal(m, b)
}
func (m *Indicator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Indicator.Marshal(b, m, deterministic)
}
func (m *Indicator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Indicator.Merge(m, src)
}
func (m *Indicator) XXX_Size() int {
	return xxx_messageInfo_Indicator.Size(m)
}
func (m *Indicator) XXX_DiscardUnknown() {
	xxx_messageInfo_Indicator.DiscardUnknown(m)
}

var xxx_messageInfo_Indicator proto.InternalMessageInfo

func (m *Indicator) GetTotalRequestPerMinute() *wrappers.UInt32Value {
	if m != nil {
		return m.TotalRequestPerMinute
	}
	return nil
}

// SDK上报的服务调用统计
type ServiceStatistics struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  *ServiceStatisticsKey `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                *ServiceIndicator     `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	SdkToken             *SDKToken             `protobuf:"bytes,4,opt,name=sdk_token,json=sdkToken,proto3" json:"sdk_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ServiceStatistics) Reset()         { *m = ServiceStatistics{} }
func (m *ServiceStatistics) String() string { return proto.CompactTextString(m) }
func (*ServiceStatistics) ProtoMessage()    {}
func (*ServiceStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_a075ef0672d1cf24, []int{5}
}

func (m *ServiceStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStatistics.Unmarshal(m, b)
}
func (m *ServiceStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStatistics.Marshal(b, m, deterministic)
}
func (m *ServiceStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStatistics.Merge(m, src)
}
func (m *ServiceStatistics) XXX_Size() int {
	return xxx_messageInfo_ServiceStatistics.Size(m)
}
func (m *ServiceStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStatistics proto.InternalMessageInfo

func (m *ServiceStatistics) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ServiceStatistics) GetKey() *ServiceStatisticsKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ServiceStatistics) GetValue() *ServiceIndicator {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ServiceStatistics) GetSdkToken() *SDKToken {
	if m != nil {
		return m.SdkToken
	}
	return nil
}

// 服务调用的上报维度
type ServiceStatisticsKey struct {
	CallerHost           *wrappers.StringValue `protobuf:"bytes,1,opt,name=caller_host,json=callerHost,proto3" json:"caller_host,omitempty"`
	Namespace            *wrappers.StringValue `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service              *wrappers.StringValue `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	InstanceHost         *wrappers.StringValue `protobuf:"bytes,4,opt,name=instance_host,json=instanceHost,proto3" json:"instance_host,omitempty"`
	Success              *wrappers.BoolValue   `protobuf:"bytes,5,opt,name=success,proto3" json:"success,omitempty"`
	ResCode              int32                 `protobuf:"varint,6,opt,name=res_code,json=resCode,proto3" json:"res_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ServiceStatisticsKey) Reset()         { *m = ServiceStatisticsKey{} }
func (m *ServiceStatisticsKey) String() string { return proto.CompactTextString(m) }
func (*ServiceStatisticsKey) ProtoMessage()    {}
func (*ServiceStatisticsKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_a075ef0672d1cf24, []int{6}
}

func (m *ServiceStatisticsKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStatisticsKey.Unmarshal(m, b)
}
func (m *ServiceStatisticsKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStatisticsKey.Marshal(b, m, deterministic)
}
func (m *ServiceStatisticsKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStatisticsKey.Merge(m, src)
}
func (m *ServiceStatisticsKey) XXX_Size() int {
	return xxx_messageInfo_ServiceStatisticsKey.Size(m)
}
func (m *ServiceStatisticsKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStatisticsKey.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStatisticsKey proto.InternalMessageInfo

func (m *ServiceStatisticsKey) GetCallerHost() *wrappers.StringValue {
	if m != nil {
		return m.CallerHost
	}
	return nil
}

func (m *ServiceStatisticsKey) GetNamespace() *wrappers.StringValue {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *ServiceStatisticsKey) GetService() *wrappers.StringValue {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *ServiceStatisticsKey) GetInstanceHost() *wrappers.StringValue {
	if m != nil {
		return m.InstanceHost
	}
	return nil
}

func (m *ServiceStatisticsKey) GetSuccess() *wrappers.BoolValue {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *ServiceStatisticsKey) GetResCode() int32 {
	if m != nil {
		return m.ResCode
	}
	return 0
}

// 服务调用的上报指标
type ServiceIndicator struct {
	TotalRequestPerMinute *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=total_request_per_minute,json=totalRequestPerMinute,proto3" json:"total_request_per_minute,omitempty"`
	TotalDelayPerMinute   *wrappers.UInt64Value `protobuf:"bytes,2,opt,name=total_delay_per_minute,json=totalDelayPerMinute,proto3" json:"total_delay_per_minute,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}              `json:"-"`
	XXX_unrecognized      []byte                `json:"-"`
	XXX_sizecache         int32                 `json:"-"`
}

func (m *ServiceIndicator) Reset()         { *m = ServiceIndicator{} }
func (m *ServiceIndicator) String() string { return proto.CompactTextString(m) }
func (*ServiceIndicator) ProtoMessage()    {}
func (*ServiceIndicator) Descriptor() ([]byte, []int) {
	return fileDescriptor_a075ef0672d1cf24, []int{7}
}

func (m *ServiceIndicator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceIndicator.Unmarshal(m, b)
}
func (m *ServiceIndicator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceIndicator.Marshal(b, m, deterministic)
}
func (m *ServiceIndicator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceIndicator.Merge(m, src)
}
func (m *ServiceIndicator) XXX_Size() int {
	return xxx_messageInfo_ServiceIndicator.Size(m)
}
func (m *ServiceIndicator) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceIndicator.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceIndicator proto.InternalMessageInfo

func (m *ServiceIndicator) GetTotalRequestPerMinute() *wrappers.UInt32Value {
	if m != nil {
		return m.TotalRequestPerMinute
	}
	return nil
}

func (m *ServiceIndicator) GetTotalDelayPerMinute() *wrappers.UInt64Value {
	if m != nil {
		return m.TotalDelayPerMinute
	}
	return nil
}

func init() {
	proto.RegisterEnum("v1.APIResultType", APIResultType_name, APIResultType_value)
	proto.RegisterType((*ServerStatistics)(nil), "v1.ServerStatistics")
	proto.RegisterType((*ServerStatisticsKey)(nil), "v1.ServerStatisticsKey")
	proto.RegisterType((*SDKAPIStatistics)(nil), "v1.SDKAPIStatistics")
	proto.RegisterType((*SDKAPIStatisticsKey)(nil), "v1.SDKAPIStatisticsKey")
	proto.RegisterType((*Indicator)(nil), "v1.Indicator")
	proto.RegisterType((*ServiceStatistics)(nil), "v1.ServiceStatistics")
	proto.RegisterType((*ServiceStatisticsKey)(nil), "v1.ServiceStatisticsKey")
	proto.RegisterType((*ServiceIndicator)(nil), "v1.ServiceIndicator")
}

func init() { proto.RegisterFile("monitorrequest.proto", fileDescriptor_a075ef0672d1cf24) }

var fileDescriptor_a075ef0672d1cf24 = []byte{
	// 717 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x4e, 0x1b, 0x49,
	0x10, 0x5e, 0x8f, 0xf1, 0x5f, 0x19, 0xb3, 0xa6, 0x61, 0x77, 0x67, 0xd1, 0x6a, 0x85, 0xbc, 0x17,
	0x40, 0x2b, 0x13, 0x7e, 0x42, 0x22, 0xa4, 0x1c, 0x1c, 0x50, 0x14, 0x8b, 0x44, 0x72, 0xc6, 0x98,
	0xab, 0x35, 0xcc, 0x54, 0x9c, 0x96, 0x87, 0xee, 0x49, 0x77, 0x8f, 0x91, 0xdf, 0x22, 0x0f, 0x94,
	0x63, 0x5e, 0x23, 0x0f, 0x91, 0x6b, 0x4e, 0x51, 0x77, 0x8f, 0x8d, 0x71, 0x08, 0x1a, 0xa3, 0xe4,
	0xd6, 0x5d, 0xfe, 0xbe, 0xaf, 0xcb, 0x55, 0x5f, 0xd5, 0xc0, 0xfa, 0x15, 0x67, 0x54, 0x71, 0x21,
	0xf0, 0x7d, 0x82, 0x52, 0x35, 0x63, 0xc1, 0x15, 0x27, 0xce, 0x68, 0x6f, 0xe3, 0xdf, 0x01, 0xe7,
	0x83, 0x08, 0x77, 0x4d, 0xe4, 0x32, 0x79, 0xbb, 0x7b, 0x2d, 0xfc, 0x38, 0x46, 0x21, 0x2d, 0x66,
	0x63, 0x45, 0x86, 0x43, 0xc5, 0x87, 0xc8, 0xec, 0xbd, 0xf1, 0x21, 0x07, 0xf5, 0x2e, 0x8a, 0x11,
	0x8a, 0xae, 0xf2, 0x15, 0x95, 0x8a, 0x06, 0x92, 0xfc, 0x0f, 0x0e, 0x0d, 0xdd, 0xdc, 0x66, 0x6e,
	0xab, 0xba, 0xff, 0x4f, 0xd3, 0x2a, 0x36, 0x27, 0x8a, 0xcd, 0xae, 0x12, 0x94, 0x0d, 0x2e, 0xfc,
	0x28, 0x41, 0xcf, 0xa1, 0x21, 0xd9, 0x86, 0xfc, 0x10, 0xc7, 0xae, 0x63, 0xe0, 0x7f, 0x35, 0x47,
	0x7b, 0xcd, 0x79, 0xc1, 0x33, 0x1c, 0x7b, 0x1a, 0x43, 0xfe, 0x83, 0xc2, 0x48, 0xf3, 0xdc, 0xbc,
	0x01, 0xd7, 0x34, 0xb8, 0xcd, 0x42, 0x1a, 0xf8, 0x8a, 0x0b, 0xcf, 0xfe, 0xd6, 0xf8, 0xe2, 0xc0,
	0xda, 0x1d, 0x0a, 0xe4, 0x19, 0x54, 0xa5, 0x09, 0xf7, 0xdf, 0x71, 0xa9, 0x32, 0xa5, 0x07, 0x96,
	0xf0, 0x92, 0x4b, 0x45, 0x9e, 0x42, 0x59, 0xa0, 0xe4, 0x89, 0x08, 0x30, 0xcd, 0xf5, 0x7e, 0xee,
	0x14, 0x4d, 0x8e, 0xa1, 0xc2, 0x63, 0x14, 0xbe, 0xa2, 0x9c, 0xa5, 0x99, 0xdf, 0x4f, 0xbd, 0x81,
	0x93, 0x47, 0xb0, 0x14, 0xf0, 0x10, 0xdd, 0xa5, 0x0c, 0x34, 0x83, 0x24, 0x87, 0x50, 0x92, 0x49,
	0x10, 0xa0, 0x94, 0x6e, 0xc1, 0x90, 0x36, 0xbe, 0x23, 0x3d, 0xe7, 0x3c, 0xb2, 0x94, 0x09, 0x54,
	0x17, 0x27, 0xc4, 0xc8, 0x1f, 0xf7, 0x85, 0xcf, 0x06, 0xe8, 0x16, 0xb3, 0x14, 0xc7, 0x10, 0x3c,
	0x8d, 0xb7, 0x36, 0x38, 0x3d, 0x6b, 0x75, 0xda, 0x3f, 0xd3, 0x06, 0x73, 0x82, 0x8b, 0xd9, 0xe0,
	0x6b, 0x1e, 0xd6, 0xee, 0x50, 0xd0, 0xff, 0x34, 0x88, 0x28, 0x32, 0xb5, 0x80, 0x0d, 0x2c, 0xc1,
	0xd8, 0xe0, 0x31, 0x94, 0x64, 0x38, 0xec, 0xfb, 0x31, 0xcd, 0xe4, 0x82, 0xa2, 0x0c, 0x87, 0xad,
	0x98, 0x92, 0x27, 0xc6, 0x3d, 0x7d, 0xd3, 0xcb, 0x2c, 0x16, 0x28, 0x09, 0x94, 0x27, 0x73, 0xed,
	0x5c, 0x7a, 0x70, 0x3b, 0x0b, 0x8b, 0xb5, 0x93, 0x9c, 0xc0, 0x4a, 0x5a, 0xa3, 0x11, 0x0a, 0xa9,
	0x6d, 0x9b, 0xc5, 0x10, 0x35, 0xcb, 0xb9, 0xb0, 0x94, 0x99, 0x42, 0xab, 0x71, 0x8c, 0x6e, 0x29,
	0x7b, 0xa1, 0xcf, 0xc7, 0x31, 0x92, 0x6d, 0x28, 0x0a, 0x94, 0x49, 0xa4, 0xdc, 0xf2, 0x66, 0x6e,
	0x6b, 0x65, 0x7f, 0x55, 0x77, 0xb9, 0xd5, 0x69, 0x7b, 0x26, 0xa8, 0x21, 0x5e, 0x0a, 0x20, 0x75,
	0xc8, 0x27, 0x34, 0x74, 0x2b, 0x9b, 0xb9, 0xad, 0x8a, 0xa7, 0x8f, 0x8d, 0x4b, 0xa8, 0x4c, 0x0d,
	0x41, 0x7a, 0xe0, 0x2a, 0xae, 0xfc, 0xa8, 0x9f, 0xae, 0xbb, 0x7e, 0x8c, 0xa2, 0x7f, 0x45, 0x59,
	0xa2, 0xf0, 0x87, 0xed, 0xef, 0xb5, 0x99, 0x3a, 0xd8, 0xb7, 0x59, 0xfd, 0x61, 0xd8, 0x9e, 0x25,
	0x77, 0x50, 0xbc, 0x36, 0xd4, 0xc6, 0xa7, 0x1c, 0xac, 0xea, 0x3d, 0x43, 0x03, 0x7c, 0xb0, 0xe9,
	0x77, 0x66, 0x4d, 0xef, 0x4e, 0x76, 0xdf, 0x2d, 0xc5, 0xa9, 0xeb, 0x77, 0x6e, 0xbb, 0x7e, 0x7d,
	0x06, 0x3d, 0x6f, 0x7e, 0xb2, 0x0d, 0x15, 0xed, 0x52, 0xb3, 0xa9, 0x53, 0xdf, 0x2c, 0xa7, 0x23,
	0x75, 0xae, 0x63, 0x5e, 0x59, 0x86, 0x43, 0x73, 0x6a, 0x7c, 0x76, 0x60, 0xfd, 0xae, 0x47, 0x4d,
	0xff, 0xfc, 0x28, 0x5a, 0x68, 0x5f, 0x5a, 0x82, 0x19, 0x94, 0x63, 0xa8, 0x30, 0xff, 0x0a, 0x65,
	0xec, 0x67, 0x5c, 0x98, 0x37, 0x70, 0x72, 0x04, 0x25, 0x69, 0x53, 0xca, 0x36, 0x2c, 0x29, 0x98,
	0xb4, 0xa0, 0x46, 0x99, 0x54, 0x3e, 0x0b, 0xd0, 0x26, 0x9d, 0x65, 0x6d, 0x2e, 0x4f, 0x28, 0x26,
	0xed, 0x87, 0xad, 0xcf, 0xbf, 0x67, 0xc6, 0x5b, 0x8f, 0x4a, 0x61, 0x3a, 0xc0, 0x8d, 0x8f, 0xe9,
	0x17, 0x72, 0xb6, 0x4d, 0xbf, 0xc8, 0x92, 0xe4, 0x0d, 0xfc, 0x69, 0x65, 0xed, 0xf0, 0xcf, 0x88,
	0x3a, 0xf7, 0x88, 0x1e, 0x1d, 0x5a, 0xd1, 0x35, 0xc3, 0x3d, 0xd5, 0xd4, 0xa9, 0xe4, 0xce, 0x2b,
	0xa8, 0xdd, 0x1a, 0x3a, 0xf2, 0x3b, 0x54, 0x7b, 0x6c, 0xc8, 0xf8, 0x35, 0xd3, 0xd7, 0xfa, 0x6f,
	0xa4, 0x0a, 0xa5, 0xae, 0x2d, 0x43, 0x3d, 0x47, 0x96, 0xa1, 0xdc, 0x93, 0x28, 0x5e, 0xf8, 0x34,
	0xaa, 0x3b, 0x1a, 0xdb, 0xe1, 0x91, 0x2f, 0xa8, 0x34, 0x81, 0xfc, 0x65, 0xd1, 0x3c, 0x7c, 0xf0,
	0x2d, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x3a, 0x29, 0xe6, 0x81, 0x08, 0x00, 0x00,
}
