// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sdkconfiguration.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SDK的配置信息
type SDKConfig struct {
	Token                *SDKToken            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Config               string               `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	TakeEffectTime       *timestamp.Timestamp `protobuf:"bytes,3,opt,name=take_effect_time,json=takeEffectTime,proto3" json:"take_effect_time,omitempty"`
	Location             string               `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Version              string               `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Client               string               `protobuf:"bytes,6,opt,name=client,proto3" json:"client,omitempty"`
	Plugins              string               `protobuf:"bytes,7,opt,name=plugins,proto3" json:"plugins,omitempty"`
	InitFinishTime       *timestamp.Timestamp `protobuf:"bytes,8,opt,name=init_finish_time,json=initFinishTime,proto3" json:"init_finish_time,omitempty"`
	ReportTime           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=report_time,json=reportTime,proto3" json:"report_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SDKConfig) Reset()         { *m = SDKConfig{} }
func (m *SDKConfig) String() string { return proto.CompactTextString(m) }
func (*SDKConfig) ProtoMessage()    {}
func (*SDKConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_8199578cb4f0af0e, []int{0}
}

func (m *SDKConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDKConfig.Unmarshal(m, b)
}
func (m *SDKConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDKConfig.Marshal(b, m, deterministic)
}
func (m *SDKConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDKConfig.Merge(m, src)
}
func (m *SDKConfig) XXX_Size() int {
	return xxx_messageInfo_SDKConfig.Size(m)
}
func (m *SDKConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SDKConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SDKConfig proto.InternalMessageInfo

func (m *SDKConfig) GetToken() *SDKToken {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *SDKConfig) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *SDKConfig) GetTakeEffectTime() *timestamp.Timestamp {
	if m != nil {
		return m.TakeEffectTime
	}
	return nil
}

func (m *SDKConfig) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *SDKConfig) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SDKConfig) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *SDKConfig) GetPlugins() string {
	if m != nil {
		return m.Plugins
	}
	return ""
}

func (m *SDKConfig) GetInitFinishTime() *timestamp.Timestamp {
	if m != nil {
		return m.InitFinishTime
	}
	return nil
}

func (m *SDKConfig) GetReportTime() *timestamp.Timestamp {
	if m != nil {
		return m.ReportTime
	}
	return nil
}

func init() {
	proto.RegisterType((*SDKConfig)(nil), "v1.SDKConfig")
}

func init() { proto.RegisterFile("sdkconfiguration.proto", fileDescriptor_8199578cb4f0af0e) }

var fileDescriptor_8199578cb4f0af0e = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0x31, 0x6f, 0xc2, 0x30,
	0x14, 0x84, 0x95, 0xb4, 0x04, 0x62, 0x2a, 0x54, 0x79, 0x40, 0x56, 0x96, 0x22, 0x26, 0x26, 0x23,
	0xda, 0xb1, 0x63, 0xd3, 0x2e, 0x6c, 0x81, 0x3d, 0x0a, 0xc1, 0x4e, 0xad, 0x04, 0x3b, 0xb2, 0x9d,
	0xfc, 0xf6, 0x8e, 0x95, 0x9f, 0x1d, 0x56, 0xc6, 0xbb, 0xf3, 0x9d, 0xbf, 0x87, 0xd6, 0xe6, 0xda,
	0xd6, 0x4a, 0x72, 0xd1, 0x0c, 0xba, 0xb2, 0x42, 0x49, 0xda, 0x6b, 0x65, 0x15, 0x8e, 0xc7, 0x43,
	0xb6, 0x32, 0xd7, 0xd6, 0xaa, 0x96, 0x05, 0x2f, 0x7b, 0x6b, 0x94, 0x6a, 0x3a, 0xb6, 0x07, 0x75,
	0x19, 0xf8, 0xde, 0x8a, 0x1b, 0x33, 0xb6, 0xba, 0xf5, 0xfe, 0xc1, 0xf6, 0x2f, 0x46, 0xe9, 0x29,
	0x3f, 0x7e, 0xc1, 0x1e, 0xde, 0xa2, 0x19, 0xb4, 0x49, 0xb4, 0x89, 0x76, 0xcb, 0xf7, 0x17, 0x3a,
	0x1e, 0xe8, 0x29, 0x3f, 0x9e, 0x9d, 0x57, 0xf8, 0x08, 0xaf, 0x51, 0xe2, 0x7f, 0x27, 0xf1, 0x26,
	0xda, 0xa5, 0x45, 0x50, 0x38, 0x47, 0xaf, 0xb6, 0x6a, 0x59, 0xc9, 0x38, 0x67, 0xb5, 0x2d, 0xdd,
	0x47, 0xe4, 0x09, 0x66, 0x32, 0xea, 0x29, 0xe8, 0x44, 0x41, 0xcf, 0x13, 0x45, 0xb1, 0x72, 0x9d,
	0x6f, 0xa8, 0x38, 0x13, 0x67, 0x68, 0xd1, 0xa9, 0x1a, 0xce, 0x22, 0xcf, 0xb0, 0x7f, 0xd7, 0x98,
	0xa0, 0xf9, 0xc8, 0xb4, 0x71, 0xd1, 0x0c, 0xa2, 0x49, 0x02, 0x53, 0x27, 0x98, 0xb4, 0x24, 0x09,
	0x4c, 0xa0, 0x5c, 0xa3, 0xef, 0x86, 0x46, 0x48, 0x43, 0xe6, 0xbe, 0x11, 0xa4, 0xa3, 0x15, 0x52,
	0xd8, 0x92, 0x0b, 0x29, 0xcc, 0xaf, 0xa7, 0x5d, 0x3c, 0xa6, 0x75, 0x9d, 0x1f, 0xa8, 0x00, 0xed,
	0x27, 0x5a, 0x6a, 0xd6, 0x2b, 0x1d, 0xce, 0x4d, 0x1f, 0x0e, 0x20, 0xff, 0xdc, 0x19, 0x97, 0x04,
	0xf2, 0x8f, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x25, 0xc6, 0xfa, 0xd0, 0x01, 0x00, 0x00,
}
