// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sdkcache.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//一次版本号变更
type RevisionHistory struct {
	//变更时间
	Time *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	//变更的次序
	ChangeSeq uint32 `protobuf:"varint,2,opt,name=change_seq,json=changeSeq,proto3" json:"change_seq,omitempty"`
	//变更后版本号
	Revision string `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	//实例变化情况
	InstanceChange *InstancesChange `protobuf:"bytes,4,opt,name=instance_change,json=instanceChange,proto3" json:"instance_change,omitempty"`
	//网格服务变化情况
	MeshServiceChange    *MeshServicesChange `protobuf:"bytes,5,opt,name=mesh_service_change,json=meshServiceChange,proto3" json:"mesh_service_change,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RevisionHistory) Reset()         { *m = RevisionHistory{} }
func (m *RevisionHistory) String() string { return proto.CompactTextString(m) }
func (*RevisionHistory) ProtoMessage()    {}
func (*RevisionHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{0}
}

func (m *RevisionHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevisionHistory.Unmarshal(m, b)
}
func (m *RevisionHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevisionHistory.Marshal(b, m, deterministic)
}
func (m *RevisionHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevisionHistory.Merge(m, src)
}
func (m *RevisionHistory) XXX_Size() int {
	return xxx_messageInfo_RevisionHistory.Size(m)
}
func (m *RevisionHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_RevisionHistory.DiscardUnknown(m)
}

var xxx_messageInfo_RevisionHistory proto.InternalMessageInfo

func (m *RevisionHistory) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *RevisionHistory) GetChangeSeq() uint32 {
	if m != nil {
		return m.ChangeSeq
	}
	return 0
}

func (m *RevisionHistory) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *RevisionHistory) GetInstanceChange() *InstancesChange {
	if m != nil {
		return m.InstanceChange
	}
	return nil
}

func (m *RevisionHistory) GetMeshServiceChange() *MeshServicesChange {
	if m != nil {
		return m.MeshServiceChange
	}
	return nil
}

// 单个网格服务的变化情况
type ChangeMeshService struct {
	MeshNamespace        string   `protobuf:"bytes,1,opt,name=mesh_namespace,json=meshNamespace,proto3" json:"mesh_namespace,omitempty"`
	MeshService          string   `protobuf:"bytes,2,opt,name=mesh_service,json=meshService,proto3" json:"mesh_service,omitempty"`
	Info                 string   `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeMeshService) Reset()         { *m = ChangeMeshService{} }
func (m *ChangeMeshService) String() string { return proto.CompactTextString(m) }
func (*ChangeMeshService) ProtoMessage()    {}
func (*ChangeMeshService) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{1}
}

func (m *ChangeMeshService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeMeshService.Unmarshal(m, b)
}
func (m *ChangeMeshService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeMeshService.Marshal(b, m, deterministic)
}
func (m *ChangeMeshService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeMeshService.Merge(m, src)
}
func (m *ChangeMeshService) XXX_Size() int {
	return xxx_messageInfo_ChangeMeshService.Size(m)
}
func (m *ChangeMeshService) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeMeshService.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeMeshService proto.InternalMessageInfo

func (m *ChangeMeshService) GetMeshNamespace() string {
	if m != nil {
		return m.MeshNamespace
	}
	return ""
}

func (m *ChangeMeshService) GetMeshService() string {
	if m != nil {
		return m.MeshService
	}
	return ""
}

func (m *ChangeMeshService) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

// 一个网格下面所有服务的变化情况
type MeshServicesChange struct {
	OldCount             uint32               `protobuf:"varint,1,opt,name=old_count,json=oldCount,proto3" json:"old_count,omitempty"`
	NewCount             uint32               `protobuf:"varint,2,opt,name=new_count,json=newCount,proto3" json:"new_count,omitempty"`
	ModifiedServices     []*ChangeMeshService `protobuf:"bytes,3,rep,name=modified_services,json=modifiedServices,proto3" json:"modified_services,omitempty"`
	AddedServices        []*ChangeMeshService `protobuf:"bytes,4,rep,name=added_services,json=addedServices,proto3" json:"added_services,omitempty"`
	DeletedServices      []*ChangeMeshService `protobuf:"bytes,5,rep,name=deleted_services,json=deletedServices,proto3" json:"deleted_services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MeshServicesChange) Reset()         { *m = MeshServicesChange{} }
func (m *MeshServicesChange) String() string { return proto.CompactTextString(m) }
func (*MeshServicesChange) ProtoMessage()    {}
func (*MeshServicesChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{2}
}

func (m *MeshServicesChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshServicesChange.Unmarshal(m, b)
}
func (m *MeshServicesChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshServicesChange.Marshal(b, m, deterministic)
}
func (m *MeshServicesChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshServicesChange.Merge(m, src)
}
func (m *MeshServicesChange) XXX_Size() int {
	return xxx_messageInfo_MeshServicesChange.Size(m)
}
func (m *MeshServicesChange) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshServicesChange.DiscardUnknown(m)
}

var xxx_messageInfo_MeshServicesChange proto.InternalMessageInfo

func (m *MeshServicesChange) GetOldCount() uint32 {
	if m != nil {
		return m.OldCount
	}
	return 0
}

func (m *MeshServicesChange) GetNewCount() uint32 {
	if m != nil {
		return m.NewCount
	}
	return 0
}

func (m *MeshServicesChange) GetModifiedServices() []*ChangeMeshService {
	if m != nil {
		return m.ModifiedServices
	}
	return nil
}

func (m *MeshServicesChange) GetAddedServices() []*ChangeMeshService {
	if m != nil {
		return m.AddedServices
	}
	return nil
}

func (m *MeshServicesChange) GetDeletedServices() []*ChangeMeshService {
	if m != nil {
		return m.DeletedServices
	}
	return nil
}

// 一个网格下面所有服务的变化情况
type MeshServicesHistory struct {
	// 版本号变更
	Revision             []*RevisionHistory `protobuf:"bytes,1,rep,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MeshServicesHistory) Reset()         { *m = MeshServicesHistory{} }
func (m *MeshServicesHistory) String() string { return proto.CompactTextString(m) }
func (*MeshServicesHistory) ProtoMessage()    {}
func (*MeshServicesHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{3}
}

func (m *MeshServicesHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshServicesHistory.Unmarshal(m, b)
}
func (m *MeshServicesHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshServicesHistory.Marshal(b, m, deterministic)
}
func (m *MeshServicesHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshServicesHistory.Merge(m, src)
}
func (m *MeshServicesHistory) XXX_Size() int {
	return xxx_messageInfo_MeshServicesHistory.Size(m)
}
func (m *MeshServicesHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshServicesHistory.DiscardUnknown(m)
}

var xxx_messageInfo_MeshServicesHistory proto.InternalMessageInfo

func (m *MeshServicesHistory) GetRevision() []*RevisionHistory {
	if m != nil {
		return m.Revision
	}
	return nil
}

// 一个网格服务的版本变化情况
type SingleMeshServiceHistory struct {
	MeshNamespace        string             `protobuf:"bytes,1,opt,name=mesh_namespace,json=meshNamespace,proto3" json:"mesh_namespace,omitempty"`
	MeshService          string             `protobuf:"bytes,2,opt,name=mesh_service,json=meshService,proto3" json:"mesh_service,omitempty"`
	Revision             []*RevisionHistory `protobuf:"bytes,3,rep,name=revision,proto3" json:"revision,omitempty"`
	MeshServiceDeleted   bool               `protobuf:"varint,4,opt,name=mesh_service_deleted,json=meshServiceDeleted,proto3" json:"mesh_service_deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SingleMeshServiceHistory) Reset()         { *m = SingleMeshServiceHistory{} }
func (m *SingleMeshServiceHistory) String() string { return proto.CompactTextString(m) }
func (*SingleMeshServiceHistory) ProtoMessage()    {}
func (*SingleMeshServiceHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{4}
}

func (m *SingleMeshServiceHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleMeshServiceHistory.Unmarshal(m, b)
}
func (m *SingleMeshServiceHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleMeshServiceHistory.Marshal(b, m, deterministic)
}
func (m *SingleMeshServiceHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleMeshServiceHistory.Merge(m, src)
}
func (m *SingleMeshServiceHistory) XXX_Size() int {
	return xxx_messageInfo_SingleMeshServiceHistory.Size(m)
}
func (m *SingleMeshServiceHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleMeshServiceHistory.DiscardUnknown(m)
}

var xxx_messageInfo_SingleMeshServiceHistory proto.InternalMessageInfo

func (m *SingleMeshServiceHistory) GetMeshNamespace() string {
	if m != nil {
		return m.MeshNamespace
	}
	return ""
}

func (m *SingleMeshServiceHistory) GetMeshService() string {
	if m != nil {
		return m.MeshService
	}
	return ""
}

func (m *SingleMeshServiceHistory) GetRevision() []*RevisionHistory {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *SingleMeshServiceHistory) GetMeshServiceDeleted() bool {
	if m != nil {
		return m.MeshServiceDeleted
	}
	return false
}

//路由变更历史
type RoutingHistory struct {
	//版本号变更
	Revision             []*RevisionHistory `protobuf:"bytes,1,rep,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RoutingHistory) Reset()         { *m = RoutingHistory{} }
func (m *RoutingHistory) String() string { return proto.CompactTextString(m) }
func (*RoutingHistory) ProtoMessage()    {}
func (*RoutingHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{5}
}

func (m *RoutingHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutingHistory.Unmarshal(m, b)
}
func (m *RoutingHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutingHistory.Marshal(b, m, deterministic)
}
func (m *RoutingHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutingHistory.Merge(m, src)
}
func (m *RoutingHistory) XXX_Size() int {
	return xxx_messageInfo_RoutingHistory.Size(m)
}
func (m *RoutingHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutingHistory.DiscardUnknown(m)
}

var xxx_messageInfo_RoutingHistory proto.InternalMessageInfo

func (m *RoutingHistory) GetRevision() []*RevisionHistory {
	if m != nil {
		return m.Revision
	}
	return nil
}

//一个实例信息
type ChangeInstance struct {
	VpcId                string   `protobuf:"bytes,1,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Info                 string   `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeInstance) Reset()         { *m = ChangeInstance{} }
func (m *ChangeInstance) String() string { return proto.CompactTextString(m) }
func (*ChangeInstance) ProtoMessage()    {}
func (*ChangeInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{6}
}

func (m *ChangeInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeInstance.Unmarshal(m, b)
}
func (m *ChangeInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeInstance.Marshal(b, m, deterministic)
}
func (m *ChangeInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeInstance.Merge(m, src)
}
func (m *ChangeInstance) XXX_Size() int {
	return xxx_messageInfo_ChangeInstance.Size(m)
}
func (m *ChangeInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeInstance.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeInstance proto.InternalMessageInfo

func (m *ChangeInstance) GetVpcId() string {
	if m != nil {
		return m.VpcId
	}
	return ""
}

func (m *ChangeInstance) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ChangeInstance) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ChangeInstance) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

//实例信息的变化情况
type InstancesChange struct {
	OldCount             uint32            `protobuf:"varint,1,opt,name=old_count,json=oldCount,proto3" json:"old_count,omitempty"`
	NewCount             uint32            `protobuf:"varint,2,opt,name=new_count,json=newCount,proto3" json:"new_count,omitempty"`
	ModifiedInstances    []*ChangeInstance `protobuf:"bytes,3,rep,name=modified_instances,json=modifiedInstances,proto3" json:"modified_instances,omitempty"`
	AddedInstances       []*ChangeInstance `protobuf:"bytes,4,rep,name=added_instances,json=addedInstances,proto3" json:"added_instances,omitempty"`
	DeletedInstances     []*ChangeInstance `protobuf:"bytes,5,rep,name=deleted_instances,json=deletedInstances,proto3" json:"deleted_instances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InstancesChange) Reset()         { *m = InstancesChange{} }
func (m *InstancesChange) String() string { return proto.CompactTextString(m) }
func (*InstancesChange) ProtoMessage()    {}
func (*InstancesChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{7}
}

func (m *InstancesChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstancesChange.Unmarshal(m, b)
}
func (m *InstancesChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstancesChange.Marshal(b, m, deterministic)
}
func (m *InstancesChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstancesChange.Merge(m, src)
}
func (m *InstancesChange) XXX_Size() int {
	return xxx_messageInfo_InstancesChange.Size(m)
}
func (m *InstancesChange) XXX_DiscardUnknown() {
	xxx_messageInfo_InstancesChange.DiscardUnknown(m)
}

var xxx_messageInfo_InstancesChange proto.InternalMessageInfo

func (m *InstancesChange) GetOldCount() uint32 {
	if m != nil {
		return m.OldCount
	}
	return 0
}

func (m *InstancesChange) GetNewCount() uint32 {
	if m != nil {
		return m.NewCount
	}
	return 0
}

func (m *InstancesChange) GetModifiedInstances() []*ChangeInstance {
	if m != nil {
		return m.ModifiedInstances
	}
	return nil
}

func (m *InstancesChange) GetAddedInstances() []*ChangeInstance {
	if m != nil {
		return m.AddedInstances
	}
	return nil
}

func (m *InstancesChange) GetDeletedInstances() []*ChangeInstance {
	if m != nil {
		return m.DeletedInstances
	}
	return nil
}

//实例变更历史
type InstancesHistory struct {
	//版本号变更
	Revision             []*RevisionHistory `protobuf:"bytes,1,rep,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *InstancesHistory) Reset()         { *m = InstancesHistory{} }
func (m *InstancesHistory) String() string { return proto.CompactTextString(m) }
func (*InstancesHistory) ProtoMessage()    {}
func (*InstancesHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{8}
}

func (m *InstancesHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstancesHistory.Unmarshal(m, b)
}
func (m *InstancesHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstancesHistory.Marshal(b, m, deterministic)
}
func (m *InstancesHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstancesHistory.Merge(m, src)
}
func (m *InstancesHistory) XXX_Size() int {
	return xxx_messageInfo_InstancesHistory.Size(m)
}
func (m *InstancesHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_InstancesHistory.DiscardUnknown(m)
}

var xxx_messageInfo_InstancesHistory proto.InternalMessageInfo

func (m *InstancesHistory) GetRevision() []*RevisionHistory {
	if m != nil {
		return m.Revision
	}
	return nil
}

//一个单独限流规则（具备一个ruleId）的变更历史
type SingleRateLimitRuleHistory struct {
	RuleId               string             `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Revision             []*RevisionHistory `protobuf:"bytes,2,rep,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SingleRateLimitRuleHistory) Reset()         { *m = SingleRateLimitRuleHistory{} }
func (m *SingleRateLimitRuleHistory) String() string { return proto.CompactTextString(m) }
func (*SingleRateLimitRuleHistory) ProtoMessage()    {}
func (*SingleRateLimitRuleHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{9}
}

func (m *SingleRateLimitRuleHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleRateLimitRuleHistory.Unmarshal(m, b)
}
func (m *SingleRateLimitRuleHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleRateLimitRuleHistory.Marshal(b, m, deterministic)
}
func (m *SingleRateLimitRuleHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleRateLimitRuleHistory.Merge(m, src)
}
func (m *SingleRateLimitRuleHistory) XXX_Size() int {
	return xxx_messageInfo_SingleRateLimitRuleHistory.Size(m)
}
func (m *SingleRateLimitRuleHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleRateLimitRuleHistory.DiscardUnknown(m)
}

var xxx_messageInfo_SingleRateLimitRuleHistory proto.InternalMessageInfo

func (m *SingleRateLimitRuleHistory) GetRuleId() string {
	if m != nil {
		return m.RuleId
	}
	return ""
}

func (m *SingleRateLimitRuleHistory) GetRevision() []*RevisionHistory {
	if m != nil {
		return m.Revision
	}
	return nil
}

//限流规则（各个单独限流规则的汇总）变更历史
type RateLimitHistory struct {
	//版本号变更
	Revision             []*RevisionHistory `protobuf:"bytes,1,rep,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RateLimitHistory) Reset()         { *m = RateLimitHistory{} }
func (m *RateLimitHistory) String() string { return proto.CompactTextString(m) }
func (*RateLimitHistory) ProtoMessage()    {}
func (*RateLimitHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{10}
}

func (m *RateLimitHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateLimitHistory.Unmarshal(m, b)
}
func (m *RateLimitHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateLimitHistory.Marshal(b, m, deterministic)
}
func (m *RateLimitHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateLimitHistory.Merge(m, src)
}
func (m *RateLimitHistory) XXX_Size() int {
	return xxx_messageInfo_RateLimitHistory.Size(m)
}
func (m *RateLimitHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_RateLimitHistory.DiscardUnknown(m)
}

var xxx_messageInfo_RateLimitHistory proto.InternalMessageInfo

func (m *RateLimitHistory) GetRevision() []*RevisionHistory {
	if m != nil {
		return m.Revision
	}
	return nil
}

//上报的服务信息
type ServiceInfo struct {
	//该条记录的唯一id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//sdk标识
	SdkToken  *SDKToken `protobuf:"bytes,2,opt,name=sdk_token,json=sdkToken,proto3" json:"sdk_token,omitempty"`
	Namespace string    `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service   string    `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	//服务实例的版本变化
	InstancesHistory *InstancesHistory `protobuf:"bytes,5,opt,name=instances_history,json=instancesHistory,proto3" json:"instances_history,omitempty"`
	//服务的实例数据已从sdk中删除（过期淘汰或者server删除了）
	InstanceEliminated bool `protobuf:"varint,6,opt,name=instance_eliminated,json=instanceEliminated,proto3" json:"instance_eliminated,omitempty"`
	//该服务对应的路由变化情况
	RoutingHistory *RoutingHistory `protobuf:"bytes,7,opt,name=routing_history,json=routingHistory,proto3" json:"routing_history,omitempty"`
	//服务的路由数据已从sdk中删除（过期淘汰或者server删除了）
	RoutingEliminated bool `protobuf:"varint,8,opt,name=routing_eliminated,json=routingEliminated,proto3" json:"routing_eliminated,omitempty"`
	//服务对应的限流规则版本
	RateLimitHistory *RateLimitHistory `protobuf:"bytes,9,opt,name=rate_limit_history,json=rateLimitHistory,proto3" json:"rate_limit_history,omitempty"`
	//各个单独限流规则的版本变更历史
	SingleRateLimitHistories []*SingleRateLimitRuleHistory `protobuf:"bytes,10,rep,name=single_rate_limit_histories,json=singleRateLimitHistories,proto3" json:"single_rate_limit_histories,omitempty"`
	//服务的限流规则数据已从sdk中删除（过期淘汰或者server删除了）
	RateLimitEliminated  bool     `protobuf:"varint,11,opt,name=rate_limit_eliminated,json=rateLimitEliminated,proto3" json:"rate_limit_eliminated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{11}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServiceInfo) GetSdkToken() *SDKToken {
	if m != nil {
		return m.SdkToken
	}
	return nil
}

func (m *ServiceInfo) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ServiceInfo) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ServiceInfo) GetInstancesHistory() *InstancesHistory {
	if m != nil {
		return m.InstancesHistory
	}
	return nil
}

func (m *ServiceInfo) GetInstanceEliminated() bool {
	if m != nil {
		return m.InstanceEliminated
	}
	return false
}

func (m *ServiceInfo) GetRoutingHistory() *RoutingHistory {
	if m != nil {
		return m.RoutingHistory
	}
	return nil
}

func (m *ServiceInfo) GetRoutingEliminated() bool {
	if m != nil {
		return m.RoutingEliminated
	}
	return false
}

func (m *ServiceInfo) GetRateLimitHistory() *RateLimitHistory {
	if m != nil {
		return m.RateLimitHistory
	}
	return nil
}

func (m *ServiceInfo) GetSingleRateLimitHistories() []*SingleRateLimitRuleHistory {
	if m != nil {
		return m.SingleRateLimitHistories
	}
	return nil
}

func (m *ServiceInfo) GetRateLimitEliminated() bool {
	if m != nil {
		return m.RateLimitEliminated
	}
	return false
}

//单个网格规则的版本变更记录
type SingleMeshResourceRuleHistory struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Revision             []*RevisionHistory `protobuf:"bytes,2,rep,name=revision,proto3" json:"revision,omitempty"`
	MeshResourceDeleted  bool               `protobuf:"varint,3,opt,name=mesh_resource_deleted,json=meshResourceDeleted,proto3" json:"mesh_resource_deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SingleMeshResourceRuleHistory) Reset()         { *m = SingleMeshResourceRuleHistory{} }
func (m *SingleMeshResourceRuleHistory) String() string { return proto.CompactTextString(m) }
func (*SingleMeshResourceRuleHistory) ProtoMessage()    {}
func (*SingleMeshResourceRuleHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{12}
}

func (m *SingleMeshResourceRuleHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleMeshResourceRuleHistory.Unmarshal(m, b)
}
func (m *SingleMeshResourceRuleHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleMeshResourceRuleHistory.Marshal(b, m, deterministic)
}
func (m *SingleMeshResourceRuleHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleMeshResourceRuleHistory.Merge(m, src)
}
func (m *SingleMeshResourceRuleHistory) XXX_Size() int {
	return xxx_messageInfo_SingleMeshResourceRuleHistory.Size(m)
}
func (m *SingleMeshResourceRuleHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleMeshResourceRuleHistory.DiscardUnknown(m)
}

var xxx_messageInfo_SingleMeshResourceRuleHistory proto.InternalMessageInfo

func (m *SingleMeshResourceRuleHistory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SingleMeshResourceRuleHistory) GetRevision() []*RevisionHistory {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *SingleMeshResourceRuleHistory) GetMeshResourceDeleted() bool {
	if m != nil {
		return m.MeshResourceDeleted
	}
	return false
}

//网格规则的版本变更记录
type MeshResourceInfo struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//sdk标识
	SdkToken *SDKToken `protobuf:"bytes,2,opt,name=sdk_token,json=sdkToken,proto3" json:"sdk_token,omitempty"`
	MeshId   string    `protobuf:"bytes,3,opt,name=mesh_id,json=meshId,proto3" json:"mesh_id,omitempty"`
	TypeUrl  string    `protobuf:"bytes,4,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	//整个规则集体的版本号变更
	Revision []*RevisionHistory `protobuf:"bytes,5,rep,name=revision,proto3" json:"revision,omitempty"`
	//整个规则是否被删除
	MeshConfigDeleted bool `protobuf:"varint,6,opt,name=mesh_config_deleted,json=meshConfigDeleted,proto3" json:"mesh_config_deleted,omitempty"`
	//各个单个规则的版本变更历史
	SingleMeshResourceHistory []*SingleMeshResourceRuleHistory `protobuf:"bytes,7,rep,name=single_mesh_resource_history,json=singleMeshResourceHistory,proto3" json:"single_mesh_resource_history,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                         `json:"-"`
	XXX_unrecognized          []byte                           `json:"-"`
	XXX_sizecache             int32                            `json:"-"`
}

func (m *MeshResourceInfo) Reset()         { *m = MeshResourceInfo{} }
func (m *MeshResourceInfo) String() string { return proto.CompactTextString(m) }
func (*MeshResourceInfo) ProtoMessage()    {}
func (*MeshResourceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{13}
}

func (m *MeshResourceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshResourceInfo.Unmarshal(m, b)
}
func (m *MeshResourceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshResourceInfo.Marshal(b, m, deterministic)
}
func (m *MeshResourceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshResourceInfo.Merge(m, src)
}
func (m *MeshResourceInfo) XXX_Size() int {
	return xxx_messageInfo_MeshResourceInfo.Size(m)
}
func (m *MeshResourceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshResourceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MeshResourceInfo proto.InternalMessageInfo

func (m *MeshResourceInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MeshResourceInfo) GetSdkToken() *SDKToken {
	if m != nil {
		return m.SdkToken
	}
	return nil
}

func (m *MeshResourceInfo) GetMeshId() string {
	if m != nil {
		return m.MeshId
	}
	return ""
}

func (m *MeshResourceInfo) GetTypeUrl() string {
	if m != nil {
		return m.TypeUrl
	}
	return ""
}

func (m *MeshResourceInfo) GetRevision() []*RevisionHistory {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *MeshResourceInfo) GetMeshConfigDeleted() bool {
	if m != nil {
		return m.MeshConfigDeleted
	}
	return false
}

func (m *MeshResourceInfo) GetSingleMeshResourceHistory() []*SingleMeshResourceRuleHistory {
	if m != nil {
		return m.SingleMeshResourceHistory
	}
	return nil
}

//网格服务的版本变更记录
type MeshInfo struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//sdk标识
	SdkToken *SDKToken `protobuf:"bytes,2,opt,name=sdk_token,json=sdkToken,proto3" json:"sdk_token,omitempty"`
	MeshId   string    `protobuf:"bytes,3,opt,name=mesh_id,json=meshId,proto3" json:"mesh_id,omitempty"`
	//整个订阅服务集体的版本号变更
	Revision []*RevisionHistory `protobuf:"bytes,4,rep,name=revision,proto3" json:"revision,omitempty"`
	//整个网格是否被删除
	MeshDeleted bool `protobuf:"varint,5,opt,name=mesh_deleted,json=meshDeleted,proto3" json:"mesh_deleted,omitempty"`
	//网格服务的版本变化
	MeshServicesHistory *MeshServicesHistory `protobuf:"bytes,6,opt,name=mesh_services_history,json=meshServicesHistory,proto3" json:"mesh_services_history,omitempty"`
	//各个单个规则的版本变更历史
	SingleMeshServiceHistory []*SingleMeshServiceHistory `protobuf:"bytes,7,rep,name=single_mesh_service_history,json=singleMeshServiceHistory,proto3" json:"single_mesh_service_history,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                    `json:"-"`
	XXX_unrecognized         []byte                      `json:"-"`
	XXX_sizecache            int32                       `json:"-"`
}

func (m *MeshInfo) Reset()         { *m = MeshInfo{} }
func (m *MeshInfo) String() string { return proto.CompactTextString(m) }
func (*MeshInfo) ProtoMessage()    {}
func (*MeshInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ae4e6f7dcbcbecb, []int{14}
}

func (m *MeshInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshInfo.Unmarshal(m, b)
}
func (m *MeshInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshInfo.Marshal(b, m, deterministic)
}
func (m *MeshInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshInfo.Merge(m, src)
}
func (m *MeshInfo) XXX_Size() int {
	return xxx_messageInfo_MeshInfo.Size(m)
}
func (m *MeshInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MeshInfo proto.InternalMessageInfo

func (m *MeshInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MeshInfo) GetSdkToken() *SDKToken {
	if m != nil {
		return m.SdkToken
	}
	return nil
}

func (m *MeshInfo) GetMeshId() string {
	if m != nil {
		return m.MeshId
	}
	return ""
}

func (m *MeshInfo) GetRevision() []*RevisionHistory {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *MeshInfo) GetMeshDeleted() bool {
	if m != nil {
		return m.MeshDeleted
	}
	return false
}

func (m *MeshInfo) GetMeshServicesHistory() *MeshServicesHistory {
	if m != nil {
		return m.MeshServicesHistory
	}
	return nil
}

func (m *MeshInfo) GetSingleMeshServiceHistory() []*SingleMeshServiceHistory {
	if m != nil {
		return m.SingleMeshServiceHistory
	}
	return nil
}

func init() {
	proto.RegisterType((*RevisionHistory)(nil), "v1.RevisionHistory")
	proto.RegisterType((*ChangeMeshService)(nil), "v1.ChangeMeshService")
	proto.RegisterType((*MeshServicesChange)(nil), "v1.MeshServicesChange")
	proto.RegisterType((*MeshServicesHistory)(nil), "v1.MeshServicesHistory")
	proto.RegisterType((*SingleMeshServiceHistory)(nil), "v1.SingleMeshServiceHistory")
	proto.RegisterType((*RoutingHistory)(nil), "v1.RoutingHistory")
	proto.RegisterType((*ChangeInstance)(nil), "v1.ChangeInstance")
	proto.RegisterType((*InstancesChange)(nil), "v1.InstancesChange")
	proto.RegisterType((*InstancesHistory)(nil), "v1.InstancesHistory")
	proto.RegisterType((*SingleRateLimitRuleHistory)(nil), "v1.SingleRateLimitRuleHistory")
	proto.RegisterType((*RateLimitHistory)(nil), "v1.RateLimitHistory")
	proto.RegisterType((*ServiceInfo)(nil), "v1.ServiceInfo")
	proto.RegisterType((*SingleMeshResourceRuleHistory)(nil), "v1.SingleMeshResourceRuleHistory")
	proto.RegisterType((*MeshResourceInfo)(nil), "v1.MeshResourceInfo")
	proto.RegisterType((*MeshInfo)(nil), "v1.MeshInfo")
}

func init() { proto.RegisterFile("sdkcache.proto", fileDescriptor_4ae4e6f7dcbcbecb) }

var fileDescriptor_4ae4e6f7dcbcbecb = []byte{
	// 1016 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x72, 0x1b, 0x45,
	0x10, 0x2e, 0xad, 0x25, 0x59, 0x6a, 0x45, 0x7f, 0xa3, 0x18, 0x2b, 0x8a, 0x03, 0x8e, 0xaa, 0xa8,
	0x32, 0x07, 0x64, 0x62, 0x8e, 0xa4, 0x0a, 0x1c, 0x85, 0x54, 0x54, 0x01, 0x0e, 0xe3, 0x70, 0xa2,
	0xa8, 0xad, 0xf5, 0xee, 0x48, 0x9a, 0xf2, 0xee, 0x8e, 0xbc, 0xb3, 0x52, 0x2a, 0x57, 0xce, 0x9c,
	0x38, 0xf1, 0x26, 0xbc, 0x01, 0xbc, 0x04, 0x0f, 0x43, 0xcd, 0xef, 0xce, 0x4a, 0x38, 0x18, 0x07,
	0x6e, 0x33, 0xdd, 0xd3, 0xfd, 0xf5, 0xcf, 0xd7, 0x33, 0x03, 0x1d, 0x1e, 0x5d, 0x85, 0x41, 0xb8,
	0x24, 0x93, 0x55, 0xc6, 0x72, 0x86, 0xbc, 0xcd, 0x93, 0x91, 0x90, 0xe5, 0xec, 0x8a, 0xa4, 0x4a,
	0x36, 0xfa, 0x68, 0xc1, 0xd8, 0x22, 0x26, 0xa7, 0x72, 0x77, 0xb9, 0x9e, 0x9f, 0xe6, 0x34, 0x21,
	0x3c, 0x0f, 0x92, 0x95, 0x3a, 0x30, 0xfe, 0xc9, 0x83, 0x2e, 0x26, 0x1b, 0xca, 0x29, 0x4b, 0x5f,
	0x52, 0x9e, 0xb3, 0xec, 0x2d, 0x9a, 0x40, 0x55, 0x1c, 0x1b, 0x56, 0x8e, 0x2b, 0x27, 0xad, 0xb3,
	0xd1, 0x44, 0xf9, 0x98, 0x18, 0x1f, 0x93, 0xd7, 0xc6, 0x07, 0x96, 0xe7, 0xd0, 0x23, 0x80, 0x70,
	0x19, 0xa4, 0x0b, 0xe2, 0x73, 0x72, 0x3d, 0xf4, 0x8e, 0x2b, 0x27, 0x6d, 0xdc, 0x54, 0x92, 0x0b,
	0x72, 0x8d, 0x46, 0xd0, 0xc8, 0x34, 0xc2, 0x70, 0xef, 0xb8, 0x72, 0xd2, 0xc4, 0x76, 0x8f, 0x9e,
	0x42, 0x97, 0xa6, 0x3c, 0x0f, 0xd2, 0x90, 0xf8, 0xca, 0x62, 0x58, 0x95, 0xa8, 0x83, 0xc9, 0xe6,
	0xc9, 0x64, 0xa6, 0x55, 0x7c, 0x2a, 0x55, 0xb8, 0x63, 0xce, 0xaa, 0x3d, 0x7a, 0x01, 0x83, 0x84,
	0xf0, 0xa5, 0xcf, 0x49, 0xb6, 0xa1, 0x85, 0x87, 0x9a, 0xf4, 0xf0, 0x81, 0xf0, 0xf0, 0x2d, 0xe1,
	0xcb, 0x0b, 0xa5, 0x35, 0x4e, 0xfa, 0x49, 0x21, 0x53, 0xa2, 0xf1, 0x35, 0xf4, 0xd5, 0xca, 0x39,
	0x8e, 0x3e, 0x86, 0x8e, 0x74, 0x9e, 0x06, 0x09, 0xe1, 0xab, 0x20, 0x54, 0xf5, 0x68, 0xe2, 0xb6,
	0x90, 0x7e, 0x67, 0x84, 0xe8, 0x31, 0xdc, 0x73, 0x63, 0x90, 0xe9, 0x37, 0x71, 0xcb, 0x01, 0x41,
	0x08, 0xaa, 0x34, 0x9d, 0x33, 0x9d, 0xbc, 0x5c, 0x8f, 0x7f, 0xf1, 0x00, 0xed, 0x06, 0x87, 0x1e,
	0x42, 0x93, 0xc5, 0x91, 0x1f, 0xb2, 0x75, 0x9a, 0x4b, 0xbc, 0x36, 0x6e, 0xb0, 0x38, 0x9a, 0x8a,
	0xbd, 0x50, 0xa6, 0xe4, 0x8d, 0x56, 0xaa, 0x32, 0x37, 0x52, 0xf2, 0x46, 0x29, 0x9f, 0x41, 0x3f,
	0x61, 0x11, 0x9d, 0x53, 0x12, 0x99, 0x58, 0xf8, 0x70, 0xef, 0x78, 0xef, 0xa4, 0x75, 0x76, 0x20,
	0x2a, 0xb1, 0x93, 0x20, 0xee, 0x99, 0xf3, 0x26, 0x06, 0xf4, 0x14, 0x3a, 0x41, 0x14, 0xb9, 0x0e,
	0xaa, 0xef, 0x72, 0xd0, 0x96, 0x87, 0xad, 0xf5, 0x57, 0xd0, 0x8b, 0x48, 0x4c, 0x72, 0xd7, 0xbe,
	0xf6, 0x2e, 0xfb, 0xae, 0x3e, 0x6e, 0x3c, 0x8c, 0x5f, 0xc0, 0xc0, 0xad, 0x89, 0xe1, 0xe3, 0xa9,
	0x43, 0xa0, 0x8a, 0x74, 0x28, 0xd9, 0xb1, 0x45, 0xdb, 0x82, 0x55, 0xe3, 0x3f, 0x2a, 0x30, 0xbc,
	0xa0, 0xe9, 0x22, 0x76, 0xe1, 0x8c, 0xb7, 0xff, 0xae, 0xaf, 0xa7, 0x25, 0x62, 0xff, 0x73, 0x5c,
	0xe8, 0x33, 0xb8, 0x5f, 0xe2, 0xab, 0xce, 0x5f, 0x52, 0xbe, 0x81, 0x91, 0xe3, 0xfb, 0xb9, 0xd2,
	0x8c, 0xcf, 0xa1, 0x83, 0xd9, 0x3a, 0xa7, 0xe9, 0xe2, 0xce, 0xc5, 0x08, 0xa1, 0xa3, 0x4a, 0x6f,
	0xa6, 0x09, 0x1d, 0x40, 0x7d, 0xb3, 0x0a, 0x7d, 0x1a, 0xe9, 0xcc, 0x6b, 0x9b, 0x55, 0x38, 0x8b,
	0x04, 0x4d, 0x97, 0x8c, 0xe7, 0x3a, 0x53, 0xb9, 0x16, 0xb2, 0x15, 0xcb, 0x72, 0x49, 0xdd, 0x36,
	0x96, 0x6b, 0x4b, 0xe7, 0xaa, 0x43, 0xe7, 0x9f, 0x3d, 0xe8, 0x6e, 0x4d, 0xeb, 0x7b, 0x70, 0xf9,
	0x1c, 0x90, 0xe5, 0xb2, 0x19, 0x79, 0x43, 0x66, 0x54, 0x70, 0xc9, 0x00, 0x62, 0xcb, 0x7c, 0x1b,
	0x02, 0xfa, 0x02, 0xba, 0x8a, 0xca, 0x85, 0x7d, 0xf5, 0x46, 0x7b, 0xc5, 0xfa, 0xc2, 0xf8, 0x4b,
	0xe8, 0x1b, 0x26, 0x17, 0xe6, 0xb5, 0x1b, 0xcd, 0x0d, 0xed, 0xad, 0x83, 0xf1, 0x14, 0x7a, 0x76,
	0x73, 0xe7, 0xc6, 0xcd, 0x61, 0xa4, 0x48, 0x8c, 0x83, 0x9c, 0x7c, 0x43, 0x13, 0x9a, 0xe3, 0x75,
	0x6c, 0x69, 0x7c, 0x08, 0xfb, 0xd9, 0x3a, 0x26, 0x45, 0x17, 0xeb, 0x62, 0x3b, 0x8b, 0x4a, 0x38,
	0xde, 0x6d, 0x70, 0xa6, 0xd0, 0xb3, 0x08, 0x77, 0x0e, 0xf6, 0xb7, 0x2a, 0xb4, 0x34, 0x77, 0x67,
	0xe9, 0x9c, 0xa1, 0x0e, 0x78, 0x36, 0x32, 0x8f, 0x46, 0xe8, 0x13, 0x68, 0xf2, 0xe8, 0xca, 0x97,
	0x6f, 0x93, 0xec, 0x77, 0xeb, 0xec, 0x9e, 0xf0, 0x78, 0xf1, 0xfc, 0xd5, 0x6b, 0x21, 0xc3, 0x0d,
	0x1e, 0x5d, 0xc9, 0x15, 0x3a, 0x82, 0x66, 0x31, 0x9b, 0xea, 0xce, 0x2c, 0x04, 0x68, 0x08, 0xfb,
	0x66, 0x24, 0x15, 0x01, 0xcd, 0x16, 0x9d, 0x43, 0xdf, 0x76, 0xcb, 0x5f, 0xaa, 0x08, 0xf5, 0x5b,
	0x70, 0xbf, 0xf4, 0x9a, 0x98, 0xe8, 0x7b, 0x74, 0xb7, 0x47, 0x03, 0xfb, 0x1c, 0x91, 0x98, 0x26,
	0x34, 0x0d, 0xc4, 0x7c, 0xd6, 0xd5, 0x7c, 0x1a, 0xd5, 0xd7, 0x56, 0x23, 0x68, 0x96, 0xa9, 0xf9,
	0xb4, 0x88, 0xfb, 0x12, 0x51, 0xf2, 0xa4, 0x3c, 0xba, 0xb8, 0x93, 0x95, 0x47, 0xf9, 0x53, 0x40,
	0xc6, 0xd8, 0x01, 0x6b, 0x48, 0xb0, 0xbe, 0xd6, 0x38, 0x58, 0xcf, 0x00, 0x65, 0x41, 0x4e, 0x7c,
	0x21, 0xc9, 0x2d, 0x5c, 0xb3, 0x48, 0x70, 0xbb, 0x8b, 0xb8, 0x97, 0x6d, 0xf7, 0xf5, 0x47, 0x78,
	0xc8, 0x25, 0xa7, 0xfc, 0x1d, 0x57, 0x94, 0xf0, 0x21, 0xc8, 0x56, 0x7f, 0x28, 0x1b, 0x73, 0x23,
	0xf5, 0xf0, 0x90, 0x97, 0x75, 0x2f, 0x8d, 0x3d, 0x3a, 0x83, 0x03, 0xc7, 0xaf, 0x93, 0x54, 0x4b,
	0x26, 0x35, 0xb0, 0xf1, 0x14, 0x69, 0x8d, 0x7f, 0xad, 0xc0, 0xa3, 0xe2, 0xb2, 0xc6, 0x84, 0xb3,
	0x75, 0x16, 0x12, 0x97, 0xea, 0x08, 0xaa, 0xa2, 0xff, 0x9a, 0x4d, 0x72, 0xfd, 0xaf, 0x59, 0x2e,
	0x42, 0x93, 0x77, 0x6f, 0xa6, 0x01, 0xec, 0xe5, 0xbb, 0xa7, 0x42, 0x4b, 0x1c, 0x70, 0x73, 0xfb,
	0xfe, 0xee, 0x41, 0xcf, 0x0d, 0xea, 0x7d, 0x99, 0x7d, 0x08, 0xfb, 0x32, 0x06, 0x1a, 0x69, 0x5e,
	0xd7, 0xc5, 0x76, 0x16, 0xa1, 0x07, 0xd0, 0xc8, 0xdf, 0xae, 0x88, 0xbf, 0xce, 0x62, 0xc3, 0x6a,
	0xb1, 0xff, 0x3e, 0x8b, 0x4b, 0x89, 0xd6, 0x6e, 0x93, 0xe8, 0x44, 0x7f, 0x8a, 0x42, 0x96, 0xce,
	0xe9, 0xc2, 0xa6, 0xa9, 0x38, 0x2c, 0x3f, 0x3f, 0x53, 0xa9, 0xd1, 0x49, 0xa2, 0x4b, 0x38, 0xd2,
	0x94, 0x28, 0xd7, 0xa7, 0xe0, 0xb3, 0x00, 0x7d, 0x5c, 0x70, 0xe2, 0x86, 0x36, 0xe1, 0x07, 0x7c,
	0x47, 0xad, 0x55, 0xe3, 0x3f, 0x3d, 0x68, 0x08, 0xf9, 0xff, 0x56, 0x40, 0xb7, 0x4a, 0xd5, 0xdb,
	0x54, 0xc9, 0x3c, 0xef, 0xa6, 0x3c, 0x35, 0x59, 0x1e, 0xf9, 0xbc, 0x9b, 0xc2, 0xbc, 0xd2, 0x8c,
	0x31, 0x9f, 0x19, 0x5b, 0x91, 0xba, 0x8c, 0xf1, 0x70, 0xfb, 0x7f, 0x69, 0x40, 0x06, 0xc9, 0xdf,
	0xfc, 0x61, 0x7e, 0xb0, 0x83, 0x57, 0xfa, 0x01, 0x94, 0x8b, 0x7c, 0x54, 0x2e, 0x72, 0xf9, 0xe3,
	0x62, 0xc6, 0x6e, 0x57, 0x73, 0x59, 0x97, 0x5f, 0xf3, 0xcf, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0x83, 0x0e, 0x09, 0x04, 0x12, 0x0c, 0x00, 0x00,
}
