// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sdkloadbalance.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceLoadBalanceInfo struct {
	Id                   string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                *SDKToken                  `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Namespace            string                     `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service              string                     `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Loadbalancer         string                     `protobuf:"bytes,5,opt,name=loadbalancer,proto3" json:"loadbalancer,omitempty"`
	TotalChooseNum       uint32                     `protobuf:"varint,6,opt,name=total_choose_num,json=totalChooseNum,proto3" json:"total_choose_num,omitempty"`
	InstanceInfo         []*InstanceLoadBalanceInfo `protobuf:"bytes,7,rep,name=instance_info,json=instanceInfo,proto3" json:"instance_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ServiceLoadBalanceInfo) Reset()         { *m = ServiceLoadBalanceInfo{} }
func (m *ServiceLoadBalanceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceLoadBalanceInfo) ProtoMessage()    {}
func (*ServiceLoadBalanceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1340c0b27ead80e7, []int{0}
}

func (m *ServiceLoadBalanceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceLoadBalanceInfo.Unmarshal(m, b)
}
func (m *ServiceLoadBalanceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceLoadBalanceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceLoadBalanceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceLoadBalanceInfo.Merge(m, src)
}
func (m *ServiceLoadBalanceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceLoadBalanceInfo.Size(m)
}
func (m *ServiceLoadBalanceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceLoadBalanceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceLoadBalanceInfo proto.InternalMessageInfo

func (m *ServiceLoadBalanceInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServiceLoadBalanceInfo) GetToken() *SDKToken {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *ServiceLoadBalanceInfo) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ServiceLoadBalanceInfo) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ServiceLoadBalanceInfo) GetLoadbalancer() string {
	if m != nil {
		return m.Loadbalancer
	}
	return ""
}

func (m *ServiceLoadBalanceInfo) GetTotalChooseNum() uint32 {
	if m != nil {
		return m.TotalChooseNum
	}
	return 0
}

func (m *ServiceLoadBalanceInfo) GetInstanceInfo() []*InstanceLoadBalanceInfo {
	if m != nil {
		return m.InstanceInfo
	}
	return nil
}

type InstanceLoadBalanceInfo struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	VpcId                string   `protobuf:"bytes,3,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	ChooseNum            uint32   `protobuf:"varint,4,opt,name=choose_num,json=chooseNum,proto3" json:"choose_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceLoadBalanceInfo) Reset()         { *m = InstanceLoadBalanceInfo{} }
func (m *InstanceLoadBalanceInfo) String() string { return proto.CompactTextString(m) }
func (*InstanceLoadBalanceInfo) ProtoMessage()    {}
func (*InstanceLoadBalanceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1340c0b27ead80e7, []int{1}
}

func (m *InstanceLoadBalanceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceLoadBalanceInfo.Unmarshal(m, b)
}
func (m *InstanceLoadBalanceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceLoadBalanceInfo.Marshal(b, m, deterministic)
}
func (m *InstanceLoadBalanceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceLoadBalanceInfo.Merge(m, src)
}
func (m *InstanceLoadBalanceInfo) XXX_Size() int {
	return xxx_messageInfo_InstanceLoadBalanceInfo.Size(m)
}
func (m *InstanceLoadBalanceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceLoadBalanceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceLoadBalanceInfo proto.InternalMessageInfo

func (m *InstanceLoadBalanceInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *InstanceLoadBalanceInfo) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *InstanceLoadBalanceInfo) GetVpcId() string {
	if m != nil {
		return m.VpcId
	}
	return ""
}

func (m *InstanceLoadBalanceInfo) GetChooseNum() uint32 {
	if m != nil {
		return m.ChooseNum
	}
	return 0
}

func init() {
	proto.RegisterType((*ServiceLoadBalanceInfo)(nil), "v1.ServiceLoadBalanceInfo")
	proto.RegisterType((*InstanceLoadBalanceInfo)(nil), "v1.InstanceLoadBalanceInfo")
}

func init() { proto.RegisterFile("sdkloadbalance.proto", fileDescriptor_1340c0b27ead80e7) }

var fileDescriptor_1340c0b27ead80e7 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4b, 0x4b, 0xc4, 0x30,
	0x14, 0x85, 0x69, 0xe7, 0xc5, 0xdc, 0x79, 0x20, 0x17, 0x1f, 0xc1, 0x07, 0x94, 0xae, 0xba, 0x1a,
	0x98, 0xf1, 0x0f, 0x88, 0xba, 0x29, 0x8a, 0x8b, 0x8e, 0xfb, 0x92, 0x49, 0x32, 0x18, 0xda, 0x26,
	0xa1, 0xc9, 0xf4, 0x97, 0xf8, 0x83, 0xa5, 0xe9, 0x54, 0x47, 0xc1, 0x5d, 0xee, 0x39, 0xf9, 0xc8,
	0xc9, 0xb9, 0x70, 0x6e, 0x79, 0x51, 0x6a, 0xca, 0x77, 0xb4, 0xa4, 0x8a, 0x89, 0x95, 0xa9, 0xb5,
	0xd3, 0x18, 0x36, 0xeb, 0xeb, 0xa5, 0xe5, 0x85, 0xd3, 0x85, 0x50, 0x9d, 0x16, 0x7f, 0x86, 0x70,
	0xb9, 0x15, 0x75, 0x23, 0x99, 0x78, 0xd5, 0x94, 0x3f, 0x76, 0x40, 0xaa, 0xf6, 0x1a, 0x97, 0x10,
	0x4a, 0x4e, 0x82, 0x28, 0x48, 0xa6, 0x59, 0x28, 0x39, 0xc6, 0x30, 0xf2, 0x24, 0x09, 0xa3, 0x20,
	0x99, 0x6d, 0xe6, 0xab, 0x66, 0xbd, 0xda, 0x3e, 0xbf, 0xbc, 0xb7, 0x5a, 0xd6, 0x59, 0x78, 0x0b,
	0x53, 0x45, 0x2b, 0x61, 0x0d, 0x65, 0x82, 0x0c, 0x3c, 0xfa, 0x23, 0x20, 0x81, 0x89, 0xed, 0xde,
	0x22, 0x43, 0xef, 0xf5, 0x23, 0xc6, 0x30, 0x3f, 0xc9, 0x5b, 0x93, 0x91, 0xb7, 0x7f, 0x69, 0x98,
	0xc0, 0x99, 0xd3, 0x8e, 0x96, 0x39, 0xfb, 0xd0, 0xda, 0x8a, 0x5c, 0x1d, 0x2a, 0x32, 0x8e, 0x82,
	0x64, 0x91, 0x2d, 0xbd, 0xfe, 0xe4, 0xe5, 0xb7, 0x43, 0x85, 0x0f, 0xb0, 0x90, 0xca, 0xba, 0x16,
	0xcb, 0xa5, 0xda, 0x6b, 0x32, 0x89, 0x06, 0xc9, 0x6c, 0x73, 0xd3, 0x26, 0x4e, 0x8f, 0xc6, 0x9f,
	0xdf, 0x66, 0xf3, 0x9e, 0x68, 0xa7, 0xd8, 0xc2, 0xd5, 0x3f, 0x17, 0x7d, 0x2d, 0xe6, 0xbb, 0x16,
	0x83, 0x08, 0x43, 0xa3, 0x6b, 0xe7, 0x5b, 0x59, 0x64, 0xfe, 0x8c, 0x17, 0x30, 0x6e, 0x0c, 0xcb,
	0x25, 0x3f, 0x76, 0x30, 0x6a, 0x0c, 0x4b, 0x39, 0xde, 0x01, 0x9c, 0x64, 0x1f, 0x7a, 0x60, 0xca,
	0xfa, 0xd8, 0xbb, 0xb1, 0x5f, 0xc9, 0xfd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xf6, 0x02,
	0x16, 0xbe, 0x01, 0x00, 0x00,
}
